// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/ankiweb.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

struct Anki_Ankiweb_GetAddonInfoRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var clientVersion: UInt32 = 0

    var addonIds: [UInt32] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Anki_Ankiweb_GetAddonInfoResponse {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var info: [Anki_Ankiweb_AddonInfo] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Anki_Ankiweb_AddonInfo {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var id: UInt32 = 0

    var modified: Int64 = 0

    var minVersion: UInt32 = 0

    var maxVersion: UInt32 = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Anki_Ankiweb_CheckForUpdateRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var version: UInt32 = 0

    var buildhash: String = .init()

    var os: String = .init()

    var installID: Int64 = 0

    var lastMessageID: UInt32 = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Anki_Ankiweb_CheckForUpdateResponse {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var newVersion: String {
        get { _newVersion ?? String() }
        set { _newVersion = newValue }
    }

    /// Returns true if `newVersion` has been explicitly set.
    var hasNewVersion: Bool {
        _newVersion != nil
    }

    /// Clears the value of `newVersion`. Subsequent reads from it will return its default value.
    mutating func clearNewVersion() {
        _newVersion = nil
    }

    var currentTime: Int64 = 0

    var message: String {
        get { _message ?? String() }
        set { _message = newValue }
    }

    /// Returns true if `message` has been explicitly set.
    var hasMessage: Bool {
        _message != nil
    }

    /// Clears the value of `message`. Subsequent reads from it will return its default value.
    mutating func clearMessage() {
        _message = nil
    }

    var lastMessageID: UInt32 = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    private var _newVersion: String?
    private var _message: String?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "anki.ankiweb"

extension Anki_Ankiweb_GetAddonInfoRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".GetAddonInfoRequest"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}client_version\0\u{3}addon_ids\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularUInt32Field(value: &clientVersion)
                case 2: try decoder.decodeRepeatedUInt32Field(value: &addonIds)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if clientVersion != 0 {
            try visitor.visitSingularUInt32Field(value: clientVersion, fieldNumber: 1)
        }
        if !addonIds.isEmpty {
            try visitor.visitPackedUInt32Field(value: addonIds, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Ankiweb_GetAddonInfoRequest, rhs: Anki_Ankiweb_GetAddonInfoRequest) -> Bool {
        if lhs.clientVersion != rhs.clientVersion { return false }
        if lhs.addonIds != rhs.addonIds { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Ankiweb_GetAddonInfoResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".GetAddonInfoResponse"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}info\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedMessageField(value: &info)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !info.isEmpty {
            try visitor.visitRepeatedMessageField(value: info, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Ankiweb_GetAddonInfoResponse, rhs: Anki_Ankiweb_GetAddonInfoResponse) -> Bool {
        if lhs.info != rhs.info { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Ankiweb_AddonInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".AddonInfo"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}id\0\u{1}modified\0\u{3}min_version\0\u{3}max_version\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularUInt32Field(value: &id)
                case 2: try decoder.decodeSingularInt64Field(value: &modified)
                case 3: try decoder.decodeSingularUInt32Field(value: &minVersion)
                case 4: try decoder.decodeSingularUInt32Field(value: &maxVersion)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if id != 0 {
            try visitor.visitSingularUInt32Field(value: id, fieldNumber: 1)
        }
        if modified != 0 {
            try visitor.visitSingularInt64Field(value: modified, fieldNumber: 2)
        }
        if minVersion != 0 {
            try visitor.visitSingularUInt32Field(value: minVersion, fieldNumber: 3)
        }
        if maxVersion != 0 {
            try visitor.visitSingularUInt32Field(value: maxVersion, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Ankiweb_AddonInfo, rhs: Anki_Ankiweb_AddonInfo) -> Bool {
        if lhs.id != rhs.id { return false }
        if lhs.modified != rhs.modified { return false }
        if lhs.minVersion != rhs.minVersion { return false }
        if lhs.maxVersion != rhs.maxVersion { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Ankiweb_CheckForUpdateRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".CheckForUpdateRequest"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}version\0\u{1}buildhash\0\u{1}os\0\u{3}install_id\0\u{3}last_message_id\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularUInt32Field(value: &version)
                case 2: try decoder.decodeSingularStringField(value: &buildhash)
                case 3: try decoder.decodeSingularStringField(value: &os)
                case 4: try decoder.decodeSingularInt64Field(value: &installID)
                case 5: try decoder.decodeSingularUInt32Field(value: &lastMessageID)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if version != 0 {
            try visitor.visitSingularUInt32Field(value: version, fieldNumber: 1)
        }
        if !buildhash.isEmpty {
            try visitor.visitSingularStringField(value: buildhash, fieldNumber: 2)
        }
        if !os.isEmpty {
            try visitor.visitSingularStringField(value: os, fieldNumber: 3)
        }
        if installID != 0 {
            try visitor.visitSingularInt64Field(value: installID, fieldNumber: 4)
        }
        if lastMessageID != 0 {
            try visitor.visitSingularUInt32Field(value: lastMessageID, fieldNumber: 5)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Ankiweb_CheckForUpdateRequest, rhs: Anki_Ankiweb_CheckForUpdateRequest) -> Bool {
        if lhs.version != rhs.version { return false }
        if lhs.buildhash != rhs.buildhash { return false }
        if lhs.os != rhs.os { return false }
        if lhs.installID != rhs.installID { return false }
        if lhs.lastMessageID != rhs.lastMessageID { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Ankiweb_CheckForUpdateResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".CheckForUpdateResponse"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}new_version\0\u{3}current_time\0\u{1}message\0\u{3}last_message_id\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &_newVersion)
                case 2: try decoder.decodeSingularInt64Field(value: &currentTime)
                case 3: try decoder.decodeSingularStringField(value: &_message)
                case 4: try decoder.decodeSingularUInt32Field(value: &lastMessageID)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _newVersion {
            try visitor.visitSingularStringField(value: v, fieldNumber: 1)
        }
        if currentTime != 0 {
            try visitor.visitSingularInt64Field(value: currentTime, fieldNumber: 2)
        }
        try { if let v = self._message {
            try visitor.visitSingularStringField(value: v, fieldNumber: 3)
        } }()
        if lastMessageID != 0 {
            try visitor.visitSingularUInt32Field(value: lastMessageID, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Ankiweb_CheckForUpdateResponse, rhs: Anki_Ankiweb_CheckForUpdateResponse) -> Bool {
        if lhs._newVersion != rhs._newVersion { return false }
        if lhs.currentTime != rhs.currentTime { return false }
        if lhs._message != rhs._message { return false }
        if lhs.lastMessageID != rhs.lastMessageID { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
