// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/import_export.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

#if canImport(FoundationEssentials)
    import FoundationEssentials
#else
    import Foundation
#endif
import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

enum Anki_ImportExport_ImportAnkiPackageUpdateCondition: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int
    case ifNewer // = 0
    case always // = 1
    case never // = 2
    case UNRECOGNIZED(Int)

    init() {
        self = .ifNewer
    }

    init?(rawValue: Int) {
        switch rawValue {
            case 0: self = .ifNewer
            case 1: self = .always
            case 2: self = .never
            default: self = .UNRECOGNIZED(rawValue)
        }
    }

    var rawValue: Int {
        switch self {
            case .ifNewer: 0
            case .always: 1
            case .never: 2
            case let .UNRECOGNIZED(i): i
        }
    }

    /// The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Anki_ImportExport_ImportAnkiPackageUpdateCondition] = [
        .ifNewer,
        .always,
        .never,
    ]
}

struct Anki_ImportExport_ImportCollectionPackageRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var colPath: String = .init()

    var backupPath: String = .init()

    var mediaFolder: String = .init()

    var mediaDb: String = .init()

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Anki_ImportExport_ExportCollectionPackageRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var outPath: String = .init()

    var includeMedia: Bool = false

    var legacy: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Anki_ImportExport_ImportAnkiPackageOptions {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var mergeNotetypes: Bool = false

    var updateNotes: Anki_ImportExport_ImportAnkiPackageUpdateCondition = .ifNewer

    var updateNotetypes: Anki_ImportExport_ImportAnkiPackageUpdateCondition = .ifNewer

    var withScheduling: Bool = false

    var withDeckConfigs: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Anki_ImportExport_ImportAnkiPackageRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var packagePath: String = .init()

    var options: Anki_ImportExport_ImportAnkiPackageOptions {
        get { _options ?? Anki_ImportExport_ImportAnkiPackageOptions() }
        set { _options = newValue }
    }

    /// Returns true if `options` has been explicitly set.
    var hasOptions: Bool {
        _options != nil
    }

    /// Clears the value of `options`. Subsequent reads from it will return its default value.
    mutating func clearOptions() {
        _options = nil
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _options: Anki_ImportExport_ImportAnkiPackageOptions?
}

struct Anki_ImportExport_ImportResponse: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var changes: Anki_Collection_OpChanges {
        get { _storage._changes ?? Anki_Collection_OpChanges() }
        set { _uniqueStorage()._changes = newValue }
    }

    /// Returns true if `changes` has been explicitly set.
    var hasChanges: Bool {
        _storage._changes != nil
    }

    /// Clears the value of `changes`. Subsequent reads from it will return its default value.
    mutating func clearChanges() {
        _uniqueStorage()._changes = nil
    }

    var log: Anki_ImportExport_ImportResponse.Log {
        get { _storage._log ?? Anki_ImportExport_ImportResponse.Log() }
        set { _uniqueStorage()._log = newValue }
    }

    /// Returns true if `log` has been explicitly set.
    var hasLog: Bool {
        _storage._log != nil
    }

    /// Clears the value of `log`. Subsequent reads from it will return its default value.
    mutating func clearLog() {
        _uniqueStorage()._log = nil
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    struct Note {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var id: Anki_Notes_NoteId {
            get { _id ?? Anki_Notes_NoteId() }
            set { _id = newValue }
        }

        /// Returns true if `id` has been explicitly set.
        var hasID: Bool {
            _id != nil
        }

        /// Clears the value of `id`. Subsequent reads from it will return its default value.
        mutating func clearID() {
            _id = nil
        }

        var fields: [String] = []

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}

        fileprivate var _id: Anki_Notes_NoteId?
    }

    struct Log {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var new: [Anki_ImportExport_ImportResponse.Note] = []

        var updated: [Anki_ImportExport_ImportResponse.Note] = []

        var duplicate: [Anki_ImportExport_ImportResponse.Note] = []

        var conflicting: [Anki_ImportExport_ImportResponse.Note] = []

        var firstFieldMatch: [Anki_ImportExport_ImportResponse.Note] = []

        var missingNotetype: [Anki_ImportExport_ImportResponse.Note] = []

        var missingDeck: [Anki_ImportExport_ImportResponse.Note] = []

        var emptyFirstField: [Anki_ImportExport_ImportResponse.Note] = []

        var dupeResolution: Anki_ImportExport_CsvMetadata.DupeResolution = .update

        var foundNotes: UInt32 = 0

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}
    }

    init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
}

struct Anki_ImportExport_ExportAnkiPackageRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var outPath: String = .init()

    var options: Anki_ImportExport_ExportAnkiPackageOptions {
        get { _options ?? Anki_ImportExport_ExportAnkiPackageOptions() }
        set { _options = newValue }
    }

    /// Returns true if `options` has been explicitly set.
    var hasOptions: Bool {
        _options != nil
    }

    /// Clears the value of `options`. Subsequent reads from it will return its default value.
    mutating func clearOptions() {
        _options = nil
    }

    var limit: Anki_ImportExport_ExportLimit {
        get { _limit ?? Anki_ImportExport_ExportLimit() }
        set { _limit = newValue }
    }

    /// Returns true if `limit` has been explicitly set.
    var hasLimit: Bool {
        _limit != nil
    }

    /// Clears the value of `limit`. Subsequent reads from it will return its default value.
    mutating func clearLimit() {
        _limit = nil
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _options: Anki_ImportExport_ExportAnkiPackageOptions?
    fileprivate var _limit: Anki_ImportExport_ExportLimit?
}

struct Anki_ImportExport_ExportAnkiPackageOptions {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var withScheduling: Bool = false

    var withDeckConfigs: Bool = false

    var withMedia: Bool = false

    var legacy: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Anki_ImportExport_PackageMetadata {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var version: Anki_ImportExport_PackageMetadata.Version = .unknown

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum Version: SwiftProtobuf.Enum, Swift.CaseIterable {
        typealias RawValue = Int
        case unknown // = 0

        /// When `meta` missing, and collection.anki2 file present.
        case legacy1 // = 1

        /// When `meta` missing, and collection.anki21 file present.
        case legacy2 // = 2

        /// Implies MediaEntry media map, and zstd compression.
        /// collection.21b file
        case latest // = 3
        case UNRECOGNIZED(Int)

        init() {
            self = .unknown
        }

        init?(rawValue: Int) {
            switch rawValue {
                case 0: self = .unknown
                case 1: self = .legacy1
                case 2: self = .legacy2
                case 3: self = .latest
                default: self = .UNRECOGNIZED(rawValue)
            }
        }

        var rawValue: Int {
            switch self {
                case .unknown: 0
                case .legacy1: 1
                case .legacy2: 2
                case .latest: 3
                case let .UNRECOGNIZED(i): i
            }
        }

        /// The compiler won't synthesize support with the UNRECOGNIZED case.
        static let allCases: [Anki_ImportExport_PackageMetadata.Version] = [
            .unknown,
            .legacy1,
            .legacy2,
            .latest,
        ]
    }
}

struct Anki_ImportExport_MediaEntries {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var entries: [Anki_ImportExport_MediaEntries.MediaEntry] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    struct MediaEntry {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var name: String = .init()

        var size: UInt32 = 0

        var sha1: Data = .init()

        //// Legacy media maps may include gaps in the media list, so the original
        //// file index is recorded when importing from a HashMap. This field is not
        //// set when exporting.
        var legacyZipFilename: UInt32 {
            get { _legacyZipFilename ?? 0 }
            set { _legacyZipFilename = newValue }
        }

        /// Returns true if `legacyZipFilename` has been explicitly set.
        var hasLegacyZipFilename: Bool {
            _legacyZipFilename != nil
        }

        /// Clears the value of `legacyZipFilename`. Subsequent reads from it will return its default value.
        mutating func clearLegacyZipFilename() {
            _legacyZipFilename = nil
        }

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}

        fileprivate var _legacyZipFilename: UInt32?
    }
}

struct Anki_ImportExport_ImportCsvRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var path: String = .init()

    var metadata: Anki_ImportExport_CsvMetadata {
        get { _metadata ?? Anki_ImportExport_CsvMetadata() }
        set { _metadata = newValue }
    }

    /// Returns true if `metadata` has been explicitly set.
    var hasMetadata: Bool {
        _metadata != nil
    }

    /// Clears the value of `metadata`. Subsequent reads from it will return its default value.
    mutating func clearMetadata() {
        _metadata = nil
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    private var _metadata: Anki_ImportExport_CsvMetadata?
}

struct Anki_ImportExport_CsvMetadataRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var path: String = .init()

    var delimiter: Anki_ImportExport_CsvMetadata.Delimiter {
        get { _delimiter ?? .tab }
        set { _delimiter = newValue }
    }

    /// Returns true if `delimiter` has been explicitly set.
    var hasDelimiter: Bool {
        _delimiter != nil
    }

    /// Clears the value of `delimiter`. Subsequent reads from it will return its default value.
    mutating func clearDelimiter() {
        _delimiter = nil
    }

    var notetypeID: Int64 {
        get { _notetypeID ?? 0 }
        set { _notetypeID = newValue }
    }

    /// Returns true if `notetypeID` has been explicitly set.
    var hasNotetypeID: Bool {
        _notetypeID != nil
    }

    /// Clears the value of `notetypeID`. Subsequent reads from it will return its default value.
    mutating func clearNotetypeID() {
        _notetypeID = nil
    }

    var deckID: Int64 {
        get { _deckID ?? 0 }
        set { _deckID = newValue }
    }

    /// Returns true if `deckID` has been explicitly set.
    var hasDeckID: Bool {
        _deckID != nil
    }

    /// Clears the value of `deckID`. Subsequent reads from it will return its default value.
    mutating func clearDeckID() {
        _deckID = nil
    }

    var isHtml: Bool {
        get { _isHtml ?? false }
        set { _isHtml = newValue }
    }

    /// Returns true if `isHtml` has been explicitly set.
    var hasIsHtml: Bool {
        _isHtml != nil
    }

    /// Clears the value of `isHtml`. Subsequent reads from it will return its default value.
    mutating func clearIsHtml() {
        _isHtml = nil
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    private var _delimiter: Anki_ImportExport_CsvMetadata.Delimiter?
    private var _notetypeID: Int64?
    private var _deckID: Int64?
    private var _isHtml: Bool?
}

/// Column indices are 1-based to make working with them in TS easier, where
/// unset numerical fields default to 0.
struct Anki_ImportExport_CsvMetadata {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var delimiter: Anki_ImportExport_CsvMetadata.Delimiter = .tab

    var isHtml: Bool = false

    var globalTags: [String] = []

    var updatedTags: [String] = []

    /// Column names as defined by the file or empty strings otherwise. Also used
    /// to determine the number of columns.
    var columnLabels: [String] = []

    var deck: Anki_ImportExport_CsvMetadata.OneOf_Deck?

    /// id of an existing deck
    var deckID: Int64 {
        get {
            if case let .deckID(v)? = deck { return v }
            return 0
        }
        set { deck = .deckID(newValue) }
    }

    /// One-based. 0 means n/a.
    var deckColumn: UInt32 {
        get {
            if case let .deckColumn(v)? = deck { return v }
            return 0
        }
        set { deck = .deckColumn(newValue) }
    }

    /// name of new deck to be created
    var deckName: String {
        get {
            if case let .deckName(v)? = deck { return v }
            return String()
        }
        set { deck = .deckName(newValue) }
    }

    var notetype: Anki_ImportExport_CsvMetadata.OneOf_Notetype?

    /// One notetype for all rows with given column mapping.
    var globalNotetype: Anki_ImportExport_CsvMetadata.MappedNotetype {
        get {
            if case let .globalNotetype(v)? = notetype { return v }
            return Anki_ImportExport_CsvMetadata.MappedNotetype()
        }
        set { notetype = .globalNotetype(newValue) }
    }

    /// Row-specific notetypes with automatic mapping by index.
    /// One-based. 0 means n/a.
    var notetypeColumn: UInt32 {
        get {
            if case let .notetypeColumn(v)? = notetype { return v }
            return 0
        }
        set { notetype = .notetypeColumn(newValue) }
    }

    /// One-based. 0 means n/a.
    var tagsColumn: UInt32 = 0

    var forceDelimiter: Bool = false

    var forceIsHtml: Bool = false

    var preview: [Anki_Generic_StringList] = []

    var guidColumn: UInt32 = 0

    var dupeResolution: Anki_ImportExport_CsvMetadata.DupeResolution = .update

    var matchScope: Anki_ImportExport_CsvMetadata.MatchScope = .notetype

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum OneOf_Deck: Equatable {
        /// id of an existing deck
        case deckID(Int64)
        /// One-based. 0 means n/a.
        case deckColumn(UInt32)
        /// name of new deck to be created
        case deckName(String)
    }

    enum OneOf_Notetype: Equatable {
        /// One notetype for all rows with given column mapping.
        case globalNotetype(Anki_ImportExport_CsvMetadata.MappedNotetype)
        /// Row-specific notetypes with automatic mapping by index.
        /// One-based. 0 means n/a.
        case notetypeColumn(UInt32)
    }

    enum DupeResolution: SwiftProtobuf.Enum, Swift.CaseIterable {
        typealias RawValue = Int
        case update // = 0
        case preserve // = 1

        /// UPDATE_IF_NEWER = 3;
        case duplicate // = 2
        case UNRECOGNIZED(Int)

        init() {
            self = .update
        }

        init?(rawValue: Int) {
            switch rawValue {
                case 0: self = .update
                case 1: self = .preserve
                case 2: self = .duplicate
                default: self = .UNRECOGNIZED(rawValue)
            }
        }

        var rawValue: Int {
            switch self {
                case .update: 0
                case .preserve: 1
                case .duplicate: 2
                case let .UNRECOGNIZED(i): i
            }
        }

        /// The compiler won't synthesize support with the UNRECOGNIZED case.
        static let allCases: [Anki_ImportExport_CsvMetadata.DupeResolution] = [
            .update,
            .preserve,
            .duplicate,
        ]
    }

    /// Order roughly in ascending expected frequency in note text, because the
    /// delimiter detection algorithm is stupidly picking the first one it
    /// encounters.
    enum Delimiter: SwiftProtobuf.Enum, Swift.CaseIterable {
        typealias RawValue = Int
        case tab // = 0
        case pipe // = 1
        case semicolon // = 2
        case colon // = 3
        case comma // = 4
        case space // = 5
        case UNRECOGNIZED(Int)

        init() {
            self = .tab
        }

        init?(rawValue: Int) {
            switch rawValue {
                case 0: self = .tab
                case 1: self = .pipe
                case 2: self = .semicolon
                case 3: self = .colon
                case 4: self = .comma
                case 5: self = .space
                default: self = .UNRECOGNIZED(rawValue)
            }
        }

        var rawValue: Int {
            switch self {
                case .tab: 0
                case .pipe: 1
                case .semicolon: 2
                case .colon: 3
                case .comma: 4
                case .space: 5
                case let .UNRECOGNIZED(i): i
            }
        }

        /// The compiler won't synthesize support with the UNRECOGNIZED case.
        static let allCases: [Anki_ImportExport_CsvMetadata.Delimiter] = [
            .tab,
            .pipe,
            .semicolon,
            .colon,
            .comma,
            .space,
        ]
    }

    enum MatchScope: SwiftProtobuf.Enum, Swift.CaseIterable {
        typealias RawValue = Int
        case notetype // = 0
        case notetypeAndDeck // = 1
        case UNRECOGNIZED(Int)

        init() {
            self = .notetype
        }

        init?(rawValue: Int) {
            switch rawValue {
                case 0: self = .notetype
                case 1: self = .notetypeAndDeck
                default: self = .UNRECOGNIZED(rawValue)
            }
        }

        var rawValue: Int {
            switch self {
                case .notetype: 0
                case .notetypeAndDeck: 1
                case let .UNRECOGNIZED(i): i
            }
        }

        /// The compiler won't synthesize support with the UNRECOGNIZED case.
        static let allCases: [Anki_ImportExport_CsvMetadata.MatchScope] = [
            .notetype,
            .notetypeAndDeck,
        ]
    }

    struct MappedNotetype {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        var id: Int64 = 0

        /// Source column indices for note fields. One-based. 0 means n/a.
        var fieldColumns: [UInt32] = []

        var unknownFields = SwiftProtobuf.UnknownStorage()

        init() {}
    }

    init() {}
}

struct Anki_ImportExport_ExportCardCsvRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var outPath: String = .init()

    var withHtml: Bool = false

    var limit: Anki_ImportExport_ExportLimit {
        get { _limit ?? Anki_ImportExport_ExportLimit() }
        set { _limit = newValue }
    }

    /// Returns true if `limit` has been explicitly set.
    var hasLimit: Bool {
        _limit != nil
    }

    /// Clears the value of `limit`. Subsequent reads from it will return its default value.
    mutating func clearLimit() {
        _limit = nil
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _limit: Anki_ImportExport_ExportLimit?
}

struct Anki_ImportExport_ExportNoteCsvRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var outPath: String = .init()

    var withHtml: Bool = false

    var withTags: Bool = false

    var withDeck: Bool = false

    var withNotetype: Bool = false

    var withGuid: Bool = false

    var limit: Anki_ImportExport_ExportLimit {
        get { _limit ?? Anki_ImportExport_ExportLimit() }
        set { _limit = newValue }
    }

    /// Returns true if `limit` has been explicitly set.
    var hasLimit: Bool {
        _limit != nil
    }

    /// Clears the value of `limit`. Subsequent reads from it will return its default value.
    mutating func clearLimit() {
        _limit = nil
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _limit: Anki_ImportExport_ExportLimit?
}

struct Anki_ImportExport_ExportLimit {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var limit: Anki_ImportExport_ExportLimit.OneOf_Limit?

    var wholeCollection: Anki_Generic_Empty {
        get {
            if case let .wholeCollection(v)? = limit { return v }
            return Anki_Generic_Empty()
        }
        set { limit = .wholeCollection(newValue) }
    }

    var deckID: Int64 {
        get {
            if case let .deckID(v)? = limit { return v }
            return 0
        }
        set { limit = .deckID(newValue) }
    }

    var noteIds: Anki_Notes_NoteIds {
        get {
            if case let .noteIds(v)? = limit { return v }
            return Anki_Notes_NoteIds()
        }
        set { limit = .noteIds(newValue) }
    }

    var cardIds: Anki_Cards_CardIds {
        get {
            if case let .cardIds(v)? = limit { return v }
            return Anki_Cards_CardIds()
        }
        set { limit = .cardIds(newValue) }
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum OneOf_Limit: Equatable {
        case wholeCollection(Anki_Generic_Empty)
        case deckID(Int64)
        case noteIds(Anki_Notes_NoteIds)
        case cardIds(Anki_Cards_CardIds)
    }

    init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "anki.import_export"

extension Anki_ImportExport_ImportAnkiPackageUpdateCondition: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{2}\0IMPORT_ANKI_PACKAGE_UPDATE_CONDITION_IF_NEWER\0\u{1}IMPORT_ANKI_PACKAGE_UPDATE_CONDITION_ALWAYS\0\u{1}IMPORT_ANKI_PACKAGE_UPDATE_CONDITION_NEVER\0"
        )
}

extension Anki_ImportExport_ImportCollectionPackageRequest: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ImportCollectionPackageRequest"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}col_path\0\u{3}backup_path\0\u{3}media_folder\0\u{3}media_db\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &colPath)
                case 2: try decoder.decodeSingularStringField(value: &backupPath)
                case 3: try decoder.decodeSingularStringField(value: &mediaFolder)
                case 4: try decoder.decodeSingularStringField(value: &mediaDb)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !colPath.isEmpty {
            try visitor.visitSingularStringField(value: colPath, fieldNumber: 1)
        }
        if !backupPath.isEmpty {
            try visitor.visitSingularStringField(value: backupPath, fieldNumber: 2)
        }
        if !mediaFolder.isEmpty {
            try visitor.visitSingularStringField(value: mediaFolder, fieldNumber: 3)
        }
        if !mediaDb.isEmpty {
            try visitor.visitSingularStringField(value: mediaDb, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (
        lhs: Anki_ImportExport_ImportCollectionPackageRequest,
        rhs: Anki_ImportExport_ImportCollectionPackageRequest
    ) -> Bool {
        if lhs.colPath != rhs.colPath { return false }
        if lhs.backupPath != rhs.backupPath { return false }
        if lhs.mediaFolder != rhs.mediaFolder { return false }
        if lhs.mediaDb != rhs.mediaDb { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_ExportCollectionPackageRequest: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ExportCollectionPackageRequest"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}out_path\0\u{3}include_media\0\u{1}legacy\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &outPath)
                case 2: try decoder.decodeSingularBoolField(value: &includeMedia)
                case 3: try decoder.decodeSingularBoolField(value: &legacy)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !outPath.isEmpty {
            try visitor.visitSingularStringField(value: outPath, fieldNumber: 1)
        }
        if includeMedia != false {
            try visitor.visitSingularBoolField(value: includeMedia, fieldNumber: 2)
        }
        if legacy != false {
            try visitor.visitSingularBoolField(value: legacy, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (
        lhs: Anki_ImportExport_ExportCollectionPackageRequest,
        rhs: Anki_ImportExport_ExportCollectionPackageRequest
    ) -> Bool {
        if lhs.outPath != rhs.outPath { return false }
        if lhs.includeMedia != rhs.includeMedia { return false }
        if lhs.legacy != rhs.legacy { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_ImportAnkiPackageOptions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ImportAnkiPackageOptions"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{3}merge_notetypes\0\u{3}update_notes\0\u{3}update_notetypes\0\u{3}with_scheduling\0\u{3}with_deck_configs\0"
        )

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularBoolField(value: &mergeNotetypes)
                case 2: try decoder.decodeSingularEnumField(value: &updateNotes)
                case 3: try decoder.decodeSingularEnumField(value: &updateNotetypes)
                case 4: try decoder.decodeSingularBoolField(value: &withScheduling)
                case 5: try decoder.decodeSingularBoolField(value: &withDeckConfigs)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if mergeNotetypes != false {
            try visitor.visitSingularBoolField(value: mergeNotetypes, fieldNumber: 1)
        }
        if updateNotes != .ifNewer {
            try visitor.visitSingularEnumField(value: updateNotes, fieldNumber: 2)
        }
        if updateNotetypes != .ifNewer {
            try visitor.visitSingularEnumField(value: updateNotetypes, fieldNumber: 3)
        }
        if withScheduling != false {
            try visitor.visitSingularBoolField(value: withScheduling, fieldNumber: 4)
        }
        if withDeckConfigs != false {
            try visitor.visitSingularBoolField(value: withDeckConfigs, fieldNumber: 5)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_ImportAnkiPackageOptions,
                    rhs: Anki_ImportExport_ImportAnkiPackageOptions) -> Bool {
        if lhs.mergeNotetypes != rhs.mergeNotetypes { return false }
        if lhs.updateNotes != rhs.updateNotes { return false }
        if lhs.updateNotetypes != rhs.updateNotetypes { return false }
        if lhs.withScheduling != rhs.withScheduling { return false }
        if lhs.withDeckConfigs != rhs.withDeckConfigs { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_ImportAnkiPackageRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ImportAnkiPackageRequest"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}package_path\0\u{1}options\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &packagePath)
                case 2: try decoder.decodeSingularMessageField(value: &_options)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !packagePath.isEmpty {
            try visitor.visitSingularStringField(value: packagePath, fieldNumber: 1)
        }
        try { if let v = self._options {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_ImportAnkiPackageRequest,
                    rhs: Anki_ImportExport_ImportAnkiPackageRequest) -> Bool {
        if lhs.packagePath != rhs.packagePath { return false }
        if lhs._options != rhs._options { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_ImportResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ImportResponse"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}changes\0\u{1}log\0")

    fileprivate class _StorageClass {
        var _changes: Anki_Collection_OpChanges?
        var _log: Anki_ImportExport_ImportResponse.Log?

        /// This property is used as the initial default value for new instances of the type.
        /// The type itself is protecting the reference to its storage via CoW semantics.
        /// This will force a copy to be made of this reference when the first mutation occurs;
        /// hence, it is safe to mark this as `nonisolated(unsafe)`.
        nonisolated(unsafe) static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            _changes = source._changes
            _log = source._log
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&_storage) {
            _storage = _StorageClass(copying: _storage)
        }
        return _storage
    }

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        _ = _uniqueStorage()
        try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                // The use of inline closures is to circumvent an issue where the compiler
                // allocates stack space for every case branch when no optimizations are
                // enabled. https://github.com/apple/swift-protobuf/issues/1034
                switch fieldNumber {
                    case 1: try decoder.decodeSingularMessageField(value: &_storage._changes)
                    case 2: try decoder.decodeSingularMessageField(value: &_storage._log)
                    default: break
                }
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every if/case branch local when no optimizations
            // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
            // https://github.com/apple/swift-protobuf/issues/1182
            try { if let v = _storage._changes {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
            } }()
            try { if let v = _storage._log {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
            } }()
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_ImportResponse, rhs: Anki_ImportExport_ImportResponse) -> Bool {
        if lhs._storage !== rhs._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((
                lhs._storage,
                rhs._storage
            )) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let rhs_storage = _args.1
                if _storage._changes != rhs_storage._changes { return false }
                if _storage._log != rhs_storage._log { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_ImportResponse.Note: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Anki_ImportExport_ImportResponse.protoMessageName + ".Note"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}fields\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_id)
                case 2: try decoder.decodeRepeatedStringField(value: &fields)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _id {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if !fields.isEmpty {
            try visitor.visitRepeatedStringField(value: fields, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_ImportResponse.Note, rhs: Anki_ImportExport_ImportResponse.Note) -> Bool {
        if lhs._id != rhs._id { return false }
        if lhs.fields != rhs.fields { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_ImportResponse.Log: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Anki_ImportExport_ImportResponse.protoMessageName + ".Log"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{1}new\0\u{1}updated\0\u{1}duplicate\0\u{1}conflicting\0\u{3}first_field_match\0\u{3}missing_notetype\0\u{3}missing_deck\0\u{3}empty_first_field\0\u{3}dupe_resolution\0\u{3}found_notes\0"
        )

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedMessageField(value: &new)
                case 2: try decoder.decodeRepeatedMessageField(value: &updated)
                case 3: try decoder.decodeRepeatedMessageField(value: &duplicate)
                case 4: try decoder.decodeRepeatedMessageField(value: &conflicting)
                case 5: try decoder.decodeRepeatedMessageField(value: &firstFieldMatch)
                case 6: try decoder.decodeRepeatedMessageField(value: &missingNotetype)
                case 7: try decoder.decodeRepeatedMessageField(value: &missingDeck)
                case 8: try decoder.decodeRepeatedMessageField(value: &emptyFirstField)
                case 9: try decoder.decodeSingularEnumField(value: &dupeResolution)
                case 10: try decoder.decodeSingularUInt32Field(value: &foundNotes)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !new.isEmpty {
            try visitor.visitRepeatedMessageField(value: new, fieldNumber: 1)
        }
        if !updated.isEmpty {
            try visitor.visitRepeatedMessageField(value: updated, fieldNumber: 2)
        }
        if !duplicate.isEmpty {
            try visitor.visitRepeatedMessageField(value: duplicate, fieldNumber: 3)
        }
        if !conflicting.isEmpty {
            try visitor.visitRepeatedMessageField(value: conflicting, fieldNumber: 4)
        }
        if !firstFieldMatch.isEmpty {
            try visitor.visitRepeatedMessageField(value: firstFieldMatch, fieldNumber: 5)
        }
        if !missingNotetype.isEmpty {
            try visitor.visitRepeatedMessageField(value: missingNotetype, fieldNumber: 6)
        }
        if !missingDeck.isEmpty {
            try visitor.visitRepeatedMessageField(value: missingDeck, fieldNumber: 7)
        }
        if !emptyFirstField.isEmpty {
            try visitor.visitRepeatedMessageField(value: emptyFirstField, fieldNumber: 8)
        }
        if dupeResolution != .update {
            try visitor.visitSingularEnumField(value: dupeResolution, fieldNumber: 9)
        }
        if foundNotes != 0 {
            try visitor.visitSingularUInt32Field(value: foundNotes, fieldNumber: 10)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_ImportResponse.Log, rhs: Anki_ImportExport_ImportResponse.Log) -> Bool {
        if lhs.new != rhs.new { return false }
        if lhs.updated != rhs.updated { return false }
        if lhs.duplicate != rhs.duplicate { return false }
        if lhs.conflicting != rhs.conflicting { return false }
        if lhs.firstFieldMatch != rhs.firstFieldMatch { return false }
        if lhs.missingNotetype != rhs.missingNotetype { return false }
        if lhs.missingDeck != rhs.missingDeck { return false }
        if lhs.emptyFirstField != rhs.emptyFirstField { return false }
        if lhs.dupeResolution != rhs.dupeResolution { return false }
        if lhs.foundNotes != rhs.foundNotes { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_ExportAnkiPackageRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ExportAnkiPackageRequest"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}out_path\0\u{1}options\0\u{1}limit\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &outPath)
                case 2: try decoder.decodeSingularMessageField(value: &_options)
                case 3: try decoder.decodeSingularMessageField(value: &_limit)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !outPath.isEmpty {
            try visitor.visitSingularStringField(value: outPath, fieldNumber: 1)
        }
        try { if let v = self._options {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        try { if let v = self._limit {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_ExportAnkiPackageRequest,
                    rhs: Anki_ImportExport_ExportAnkiPackageRequest) -> Bool {
        if lhs.outPath != rhs.outPath { return false }
        if lhs._options != rhs._options { return false }
        if lhs._limit != rhs._limit { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_ExportAnkiPackageOptions: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ExportAnkiPackageOptions"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}with_scheduling\0\u{3}with_deck_configs\0\u{3}with_media\0\u{1}legacy\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularBoolField(value: &withScheduling)
                case 2: try decoder.decodeSingularBoolField(value: &withDeckConfigs)
                case 3: try decoder.decodeSingularBoolField(value: &withMedia)
                case 4: try decoder.decodeSingularBoolField(value: &legacy)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if withScheduling != false {
            try visitor.visitSingularBoolField(value: withScheduling, fieldNumber: 1)
        }
        if withDeckConfigs != false {
            try visitor.visitSingularBoolField(value: withDeckConfigs, fieldNumber: 2)
        }
        if withMedia != false {
            try visitor.visitSingularBoolField(value: withMedia, fieldNumber: 3)
        }
        if legacy != false {
            try visitor.visitSingularBoolField(value: legacy, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_ExportAnkiPackageOptions,
                    rhs: Anki_ImportExport_ExportAnkiPackageOptions) -> Bool {
        if lhs.withScheduling != rhs.withScheduling { return false }
        if lhs.withDeckConfigs != rhs.withDeckConfigs { return false }
        if lhs.withMedia != rhs.withMedia { return false }
        if lhs.legacy != rhs.legacy { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_PackageMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".PackageMetadata"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}version\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularEnumField(value: &version)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if version != .unknown {
            try visitor.visitSingularEnumField(value: version, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_PackageMetadata, rhs: Anki_ImportExport_PackageMetadata) -> Bool {
        if lhs.version != rhs.version { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_PackageMetadata.Version: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{2}\0VERSION_UNKNOWN\0\u{1}VERSION_LEGACY_1\0\u{1}VERSION_LEGACY_2\0\u{1}VERSION_LATEST\0"
        )
}

extension Anki_ImportExport_MediaEntries: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".MediaEntries"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}entries\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedMessageField(value: &entries)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !entries.isEmpty {
            try visitor.visitRepeatedMessageField(value: entries, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_MediaEntries, rhs: Anki_ImportExport_MediaEntries) -> Bool {
        if lhs.entries != rhs.entries { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_MediaEntries.MediaEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Anki_ImportExport_MediaEntries.protoMessageName + ".MediaEntry"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}name\0\u{1}size\0\u{1}sha1\0\u{4}|\u{3}legacy_zip_filename\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &name)
                case 2: try decoder.decodeSingularUInt32Field(value: &size)
                case 3: try decoder.decodeSingularBytesField(value: &sha1)
                case 255: try decoder.decodeSingularUInt32Field(value: &_legacyZipFilename)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !name.isEmpty {
            try visitor.visitSingularStringField(value: name, fieldNumber: 1)
        }
        if size != 0 {
            try visitor.visitSingularUInt32Field(value: size, fieldNumber: 2)
        }
        if !sha1.isEmpty {
            try visitor.visitSingularBytesField(value: sha1, fieldNumber: 3)
        }
        try { if let v = self._legacyZipFilename {
            try visitor.visitSingularUInt32Field(value: v, fieldNumber: 255)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_MediaEntries.MediaEntry,
                    rhs: Anki_ImportExport_MediaEntries.MediaEntry) -> Bool {
        if lhs.name != rhs.name { return false }
        if lhs.size != rhs.size { return false }
        if lhs.sha1 != rhs.sha1 { return false }
        if lhs._legacyZipFilename != rhs._legacyZipFilename { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_ImportCsvRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ImportCsvRequest"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}path\0\u{1}metadata\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &path)
                case 2: try decoder.decodeSingularMessageField(value: &_metadata)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !path.isEmpty {
            try visitor.visitSingularStringField(value: path, fieldNumber: 1)
        }
        try { if let v = self._metadata {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_ImportCsvRequest, rhs: Anki_ImportExport_ImportCsvRequest) -> Bool {
        if lhs.path != rhs.path { return false }
        if lhs._metadata != rhs._metadata { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_CsvMetadataRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".CsvMetadataRequest"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}path\0\u{1}delimiter\0\u{3}notetype_id\0\u{3}deck_id\0\u{3}is_html\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &path)
                case 2: try decoder.decodeSingularEnumField(value: &_delimiter)
                case 3: try decoder.decodeSingularInt64Field(value: &_notetypeID)
                case 4: try decoder.decodeSingularInt64Field(value: &_deckID)
                case 5: try decoder.decodeSingularBoolField(value: &_isHtml)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !path.isEmpty {
            try visitor.visitSingularStringField(value: path, fieldNumber: 1)
        }
        try { if let v = self._delimiter {
            try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
        } }()
        try { if let v = self._notetypeID {
            try visitor.visitSingularInt64Field(value: v, fieldNumber: 3)
        } }()
        try { if let v = self._deckID {
            try visitor.visitSingularInt64Field(value: v, fieldNumber: 4)
        } }()
        try { if let v = self._isHtml {
            try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_CsvMetadataRequest, rhs: Anki_ImportExport_CsvMetadataRequest) -> Bool {
        if lhs.path != rhs.path { return false }
        if lhs._delimiter != rhs._delimiter { return false }
        if lhs._notetypeID != rhs._notetypeID { return false }
        if lhs._deckID != rhs._deckID { return false }
        if lhs._isHtml != rhs._isHtml { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_CsvMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".CsvMetadata"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{1}delimiter\0\u{3}is_html\0\u{3}global_tags\0\u{3}updated_tags\0\u{3}column_labels\0\u{3}deck_id\0\u{3}deck_column\0\u{3}global_notetype\0\u{3}notetype_column\0\u{3}tags_column\0\u{3}force_delimiter\0\u{3}force_is_html\0\u{1}preview\0\u{3}guid_column\0\u{3}dupe_resolution\0\u{3}match_scope\0\u{3}deck_name\0"
        )

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularEnumField(value: &delimiter)
                case 2: try decoder.decodeSingularBoolField(value: &isHtml)
                case 3: try decoder.decodeRepeatedStringField(value: &globalTags)
                case 4: try decoder.decodeRepeatedStringField(value: &updatedTags)
                case 5: try decoder.decodeRepeatedStringField(value: &columnLabels)
                case 6: try {
                        var v: Int64?
                        try decoder.decodeSingularInt64Field(value: &v)
                        if let v {
                            if self.deck != nil { try decoder.handleConflictingOneOf() }
                            self.deck = .deckID(v)
                        }
                    }()
                case 7: try {
                        var v: UInt32?
                        try decoder.decodeSingularUInt32Field(value: &v)
                        if let v {
                            if self.deck != nil { try decoder.handleConflictingOneOf() }
                            self.deck = .deckColumn(v)
                        }
                    }()
                case 8: try {
                        var v: Anki_ImportExport_CsvMetadata.MappedNotetype?
                        var hadOneofValue = false
                        if let current = self.notetype {
                            hadOneofValue = true
                            if case let .globalNotetype(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.notetype = .globalNotetype(v)
                        }
                    }()
                case 9: try {
                        var v: UInt32?
                        try decoder.decodeSingularUInt32Field(value: &v)
                        if let v {
                            if self.notetype != nil { try decoder.handleConflictingOneOf() }
                            self.notetype = .notetypeColumn(v)
                        }
                    }()
                case 10: try decoder.decodeSingularUInt32Field(value: &tagsColumn)
                case 11: try decoder.decodeSingularBoolField(value: &forceDelimiter)
                case 12: try decoder.decodeSingularBoolField(value: &forceIsHtml)
                case 13: try decoder.decodeRepeatedMessageField(value: &preview)
                case 14: try decoder.decodeSingularUInt32Field(value: &guidColumn)
                case 15: try decoder.decodeSingularEnumField(value: &dupeResolution)
                case 16: try decoder.decodeSingularEnumField(value: &matchScope)
                case 17: try {
                        var v: String?
                        try decoder.decodeSingularStringField(value: &v)
                        if let v {
                            if self.deck != nil { try decoder.handleConflictingOneOf() }
                            self.deck = .deckName(v)
                        }
                    }()
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if delimiter != .tab {
            try visitor.visitSingularEnumField(value: delimiter, fieldNumber: 1)
        }
        if isHtml != false {
            try visitor.visitSingularBoolField(value: isHtml, fieldNumber: 2)
        }
        if !globalTags.isEmpty {
            try visitor.visitRepeatedStringField(value: globalTags, fieldNumber: 3)
        }
        if !updatedTags.isEmpty {
            try visitor.visitRepeatedStringField(value: updatedTags, fieldNumber: 4)
        }
        if !columnLabels.isEmpty {
            try visitor.visitRepeatedStringField(value: columnLabels, fieldNumber: 5)
        }
        switch deck {
            case .deckID?: try {
                    guard case let .deckID(v)? = self.deck else { preconditionFailure() }
                    try visitor.visitSingularInt64Field(value: v, fieldNumber: 6)
                }()
            case .deckColumn?: try {
                    guard case let .deckColumn(v)? = self.deck else { preconditionFailure() }
                    try visitor.visitSingularUInt32Field(value: v, fieldNumber: 7)
                }()
            default: break
        }
        switch notetype {
            case .globalNotetype?: try {
                    guard case let .globalNotetype(v)? = self.notetype else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
                }()
            case .notetypeColumn?: try {
                    guard case let .notetypeColumn(v)? = self.notetype else { preconditionFailure() }
                    try visitor.visitSingularUInt32Field(value: v, fieldNumber: 9)
                }()
            case nil: break
        }
        if tagsColumn != 0 {
            try visitor.visitSingularUInt32Field(value: tagsColumn, fieldNumber: 10)
        }
        if forceDelimiter != false {
            try visitor.visitSingularBoolField(value: forceDelimiter, fieldNumber: 11)
        }
        if forceIsHtml != false {
            try visitor.visitSingularBoolField(value: forceIsHtml, fieldNumber: 12)
        }
        if !preview.isEmpty {
            try visitor.visitRepeatedMessageField(value: preview, fieldNumber: 13)
        }
        if guidColumn != 0 {
            try visitor.visitSingularUInt32Field(value: guidColumn, fieldNumber: 14)
        }
        if dupeResolution != .update {
            try visitor.visitSingularEnumField(value: dupeResolution, fieldNumber: 15)
        }
        if matchScope != .notetype {
            try visitor.visitSingularEnumField(value: matchScope, fieldNumber: 16)
        }
        try { if case let .deckName(v)? = self.deck {
            try visitor.visitSingularStringField(value: v, fieldNumber: 17)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_CsvMetadata, rhs: Anki_ImportExport_CsvMetadata) -> Bool {
        if lhs.delimiter != rhs.delimiter { return false }
        if lhs.isHtml != rhs.isHtml { return false }
        if lhs.globalTags != rhs.globalTags { return false }
        if lhs.updatedTags != rhs.updatedTags { return false }
        if lhs.columnLabels != rhs.columnLabels { return false }
        if lhs.deck != rhs.deck { return false }
        if lhs.notetype != rhs.notetype { return false }
        if lhs.tagsColumn != rhs.tagsColumn { return false }
        if lhs.forceDelimiter != rhs.forceDelimiter { return false }
        if lhs.forceIsHtml != rhs.forceIsHtml { return false }
        if lhs.preview != rhs.preview { return false }
        if lhs.guidColumn != rhs.guidColumn { return false }
        if lhs.dupeResolution != rhs.dupeResolution { return false }
        if lhs.matchScope != rhs.matchScope { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_CsvMetadata.DupeResolution: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UPDATE\0\u{1}PRESERVE\0\u{1}DUPLICATE\0")
}

extension Anki_ImportExport_CsvMetadata.Delimiter: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{2}\0TAB\0\u{1}PIPE\0\u{1}SEMICOLON\0\u{1}COLON\0\u{1}COMMA\0\u{1}SPACE\0")
}

extension Anki_ImportExport_CsvMetadata.MatchScope: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0NOTETYPE\0\u{1}NOTETYPE_AND_DECK\0")
}

extension Anki_ImportExport_CsvMetadata.MappedNotetype: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = Anki_ImportExport_CsvMetadata.protoMessageName + ".MappedNotetype"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{3}field_columns\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularInt64Field(value: &id)
                case 2: try decoder.decodeRepeatedUInt32Field(value: &fieldColumns)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if id != 0 {
            try visitor.visitSingularInt64Field(value: id, fieldNumber: 1)
        }
        if !fieldColumns.isEmpty {
            try visitor.visitPackedUInt32Field(value: fieldColumns, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_CsvMetadata.MappedNotetype,
                    rhs: Anki_ImportExport_CsvMetadata.MappedNotetype) -> Bool {
        if lhs.id != rhs.id { return false }
        if lhs.fieldColumns != rhs.fieldColumns { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_ExportCardCsvRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ExportCardCsvRequest"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}out_path\0\u{3}with_html\0\u{1}limit\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &outPath)
                case 2: try decoder.decodeSingularBoolField(value: &withHtml)
                case 3: try decoder.decodeSingularMessageField(value: &_limit)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !outPath.isEmpty {
            try visitor.visitSingularStringField(value: outPath, fieldNumber: 1)
        }
        if withHtml != false {
            try visitor.visitSingularBoolField(value: withHtml, fieldNumber: 2)
        }
        try { if let v = self._limit {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_ExportCardCsvRequest, rhs: Anki_ImportExport_ExportCardCsvRequest) -> Bool {
        if lhs.outPath != rhs.outPath { return false }
        if lhs.withHtml != rhs.withHtml { return false }
        if lhs._limit != rhs._limit { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_ExportNoteCsvRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ExportNoteCsvRequest"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{3}out_path\0\u{3}with_html\0\u{3}with_tags\0\u{3}with_deck\0\u{3}with_notetype\0\u{3}with_guid\0\u{1}limit\0"
        )

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &outPath)
                case 2: try decoder.decodeSingularBoolField(value: &withHtml)
                case 3: try decoder.decodeSingularBoolField(value: &withTags)
                case 4: try decoder.decodeSingularBoolField(value: &withDeck)
                case 5: try decoder.decodeSingularBoolField(value: &withNotetype)
                case 6: try decoder.decodeSingularBoolField(value: &withGuid)
                case 7: try decoder.decodeSingularMessageField(value: &_limit)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !outPath.isEmpty {
            try visitor.visitSingularStringField(value: outPath, fieldNumber: 1)
        }
        if withHtml != false {
            try visitor.visitSingularBoolField(value: withHtml, fieldNumber: 2)
        }
        if withTags != false {
            try visitor.visitSingularBoolField(value: withTags, fieldNumber: 3)
        }
        if withDeck != false {
            try visitor.visitSingularBoolField(value: withDeck, fieldNumber: 4)
        }
        if withNotetype != false {
            try visitor.visitSingularBoolField(value: withNotetype, fieldNumber: 5)
        }
        if withGuid != false {
            try visitor.visitSingularBoolField(value: withGuid, fieldNumber: 6)
        }
        try { if let v = self._limit {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_ExportNoteCsvRequest, rhs: Anki_ImportExport_ExportNoteCsvRequest) -> Bool {
        if lhs.outPath != rhs.outPath { return false }
        if lhs.withHtml != rhs.withHtml { return false }
        if lhs.withTags != rhs.withTags { return false }
        if lhs.withDeck != rhs.withDeck { return false }
        if lhs.withNotetype != rhs.withNotetype { return false }
        if lhs.withGuid != rhs.withGuid { return false }
        if lhs._limit != rhs._limit { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImportExport_ExportLimit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ExportLimit"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}whole_collection\0\u{3}deck_id\0\u{3}note_ids\0\u{3}card_ids\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try {
                        var v: Anki_Generic_Empty?
                        var hadOneofValue = false
                        if let current = self.limit {
                            hadOneofValue = true
                            if case let .wholeCollection(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.limit = .wholeCollection(v)
                        }
                    }()
                case 2: try {
                        var v: Int64?
                        try decoder.decodeSingularInt64Field(value: &v)
                        if let v {
                            if self.limit != nil { try decoder.handleConflictingOneOf() }
                            self.limit = .deckID(v)
                        }
                    }()
                case 3: try {
                        var v: Anki_Notes_NoteIds?
                        var hadOneofValue = false
                        if let current = self.limit {
                            hadOneofValue = true
                            if case let .noteIds(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.limit = .noteIds(v)
                        }
                    }()
                case 4: try {
                        var v: Anki_Cards_CardIds?
                        var hadOneofValue = false
                        if let current = self.limit {
                            hadOneofValue = true
                            if case let .cardIds(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.limit = .cardIds(v)
                        }
                    }()
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        switch limit {
            case .wholeCollection?: try {
                    guard case let .wholeCollection(v)? = self.limit else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
                }()
            case .deckID?: try {
                    guard case let .deckID(v)? = self.limit else { preconditionFailure() }
                    try visitor.visitSingularInt64Field(value: v, fieldNumber: 2)
                }()
            case .noteIds?: try {
                    guard case let .noteIds(v)? = self.limit else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
                }()
            case .cardIds?: try {
                    guard case let .cardIds(v)? = self.limit else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
                }()
            case nil: break
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_ImportExport_ExportLimit, rhs: Anki_ImportExport_ExportLimit) -> Bool {
        if lhs.limit != rhs.limit { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
