// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/media.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

#if canImport(FoundationEssentials)
    import FoundationEssentials
#else
    import Foundation
#endif
import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

struct Anki_Media_CheckMediaResponse {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var unused: [String] = []

    var missing: [String] = []

    var missingMediaNotes: [Int64] = []

    var report: String = .init()

    var haveTrash: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Anki_Media_TrashMediaFilesRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var fnames: [String] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Anki_Media_AddMediaFileRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var desiredName: String = .init()

    var data: Data = .init()

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "anki.media"

extension Anki_Media_CheckMediaResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".CheckMediaResponse"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}unused\0\u{1}missing\0\u{3}missing_media_notes\0\u{1}report\0\u{3}have_trash\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedStringField(value: &unused)
                case 2: try decoder.decodeRepeatedStringField(value: &missing)
                case 3: try decoder.decodeRepeatedInt64Field(value: &missingMediaNotes)
                case 4: try decoder.decodeSingularStringField(value: &report)
                case 5: try decoder.decodeSingularBoolField(value: &haveTrash)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !unused.isEmpty {
            try visitor.visitRepeatedStringField(value: unused, fieldNumber: 1)
        }
        if !missing.isEmpty {
            try visitor.visitRepeatedStringField(value: missing, fieldNumber: 2)
        }
        if !missingMediaNotes.isEmpty {
            try visitor.visitPackedInt64Field(value: missingMediaNotes, fieldNumber: 3)
        }
        if !report.isEmpty {
            try visitor.visitSingularStringField(value: report, fieldNumber: 4)
        }
        if haveTrash != false {
            try visitor.visitSingularBoolField(value: haveTrash, fieldNumber: 5)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Media_CheckMediaResponse, rhs: Anki_Media_CheckMediaResponse) -> Bool {
        if lhs.unused != rhs.unused { return false }
        if lhs.missing != rhs.missing { return false }
        if lhs.missingMediaNotes != rhs.missingMediaNotes { return false }
        if lhs.report != rhs.report { return false }
        if lhs.haveTrash != rhs.haveTrash { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Media_TrashMediaFilesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".TrashMediaFilesRequest"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fnames\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedStringField(value: &fnames)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !fnames.isEmpty {
            try visitor.visitRepeatedStringField(value: fnames, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Media_TrashMediaFilesRequest, rhs: Anki_Media_TrashMediaFilesRequest) -> Bool {
        if lhs.fnames != rhs.fnames { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Media_AddMediaFileRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".AddMediaFileRequest"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}desired_name\0\u{1}data\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &desiredName)
                case 2: try decoder.decodeSingularBytesField(value: &data)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !desiredName.isEmpty {
            try visitor.visitSingularStringField(value: desiredName, fieldNumber: 1)
        }
        if !data.isEmpty {
            try visitor.visitSingularBytesField(value: data, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Media_AddMediaFileRequest, rhs: Anki_Media_AddMediaFileRequest) -> Bool {
        if lhs.desiredName != rhs.desiredName { return false }
        if lhs.data != rhs.data { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
