// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/sync.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

struct Anki_Sync_SyncAuth {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var hkey: String = .init()

    var endpoint: String {
        get { _endpoint ?? String() }
        set { _endpoint = newValue }
    }

    /// Returns true if `endpoint` has been explicitly set.
    var hasEndpoint: Bool {
        _endpoint != nil
    }

    /// Clears the value of `endpoint`. Subsequent reads from it will return its default value.
    mutating func clearEndpoint() {
        _endpoint = nil
    }

    var ioTimeoutSecs: UInt32 {
        get { _ioTimeoutSecs ?? 0 }
        set { _ioTimeoutSecs = newValue }
    }

    /// Returns true if `ioTimeoutSecs` has been explicitly set.
    var hasIoTimeoutSecs: Bool {
        _ioTimeoutSecs != nil
    }

    /// Clears the value of `ioTimeoutSecs`. Subsequent reads from it will return its default value.
    mutating func clearIoTimeoutSecs() {
        _ioTimeoutSecs = nil
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _endpoint: String?
    fileprivate var _ioTimeoutSecs: UInt32?
}

struct Anki_Sync_SyncLoginRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var username: String = .init()

    var password: String = .init()

    var endpoint: String {
        get { _endpoint ?? String() }
        set { _endpoint = newValue }
    }

    /// Returns true if `endpoint` has been explicitly set.
    var hasEndpoint: Bool {
        _endpoint != nil
    }

    /// Clears the value of `endpoint`. Subsequent reads from it will return its default value.
    mutating func clearEndpoint() {
        _endpoint = nil
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _endpoint: String?
}

struct Anki_Sync_SyncStatusResponse {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var required: Anki_Sync_SyncStatusResponse.Required = .noChanges

    var newEndpoint: String {
        get { _newEndpoint ?? String() }
        set { _newEndpoint = newValue }
    }

    /// Returns true if `newEndpoint` has been explicitly set.
    var hasNewEndpoint: Bool {
        _newEndpoint != nil
    }

    /// Clears the value of `newEndpoint`. Subsequent reads from it will return its default value.
    mutating func clearNewEndpoint() {
        _newEndpoint = nil
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum Required: SwiftProtobuf.Enum, Swift.CaseIterable {
        typealias RawValue = Int
        case noChanges // = 0
        case normalSync // = 1
        case fullSync // = 2
        case UNRECOGNIZED(Int)

        init() {
            self = .noChanges
        }

        init?(rawValue: Int) {
            switch rawValue {
                case 0: self = .noChanges
                case 1: self = .normalSync
                case 2: self = .fullSync
                default: self = .UNRECOGNIZED(rawValue)
            }
        }

        var rawValue: Int {
            switch self {
                case .noChanges: 0
                case .normalSync: 1
                case .fullSync: 2
                case let .UNRECOGNIZED(i): i
            }
        }

        /// The compiler won't synthesize support with the UNRECOGNIZED case.
        static let allCases: [Anki_Sync_SyncStatusResponse.Required] = [
            .noChanges,
            .normalSync,
            .fullSync,
        ]
    }

    init() {}

    fileprivate var _newEndpoint: String?
}

struct Anki_Sync_SyncCollectionRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var auth: Anki_Sync_SyncAuth {
        get { _auth ?? Anki_Sync_SyncAuth() }
        set { _auth = newValue }
    }

    /// Returns true if `auth` has been explicitly set.
    var hasAuth: Bool {
        _auth != nil
    }

    /// Clears the value of `auth`. Subsequent reads from it will return its default value.
    mutating func clearAuth() {
        _auth = nil
    }

    var syncMedia: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _auth: Anki_Sync_SyncAuth?
}

struct Anki_Sync_SyncCollectionResponse {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var hostNumber: UInt32 = 0

    var serverMessage: String = .init()

    var required: Anki_Sync_SyncCollectionResponse.ChangesRequired = .noChanges

    var newEndpoint: String {
        get { _newEndpoint ?? String() }
        set { _newEndpoint = newValue }
    }

    /// Returns true if `newEndpoint` has been explicitly set.
    var hasNewEndpoint: Bool {
        _newEndpoint != nil
    }

    /// Clears the value of `newEndpoint`. Subsequent reads from it will return its default value.
    mutating func clearNewEndpoint() {
        _newEndpoint = nil
    }

    var serverMediaUsn: Int32 = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum ChangesRequired: SwiftProtobuf.Enum, Swift.CaseIterable {
        typealias RawValue = Int
        case noChanges // = 0
        case normalSync // = 1
        case fullSync // = 2

        /// local collection has no cards; upload not an option
        case fullDownload // = 3

        /// remote collection has no cards; download not an option
        case fullUpload // = 4
        case UNRECOGNIZED(Int)

        init() {
            self = .noChanges
        }

        init?(rawValue: Int) {
            switch rawValue {
                case 0: self = .noChanges
                case 1: self = .normalSync
                case 2: self = .fullSync
                case 3: self = .fullDownload
                case 4: self = .fullUpload
                default: self = .UNRECOGNIZED(rawValue)
            }
        }

        var rawValue: Int {
            switch self {
                case .noChanges: 0
                case .normalSync: 1
                case .fullSync: 2
                case .fullDownload: 3
                case .fullUpload: 4
                case let .UNRECOGNIZED(i): i
            }
        }

        /// The compiler won't synthesize support with the UNRECOGNIZED case.
        static let allCases: [Anki_Sync_SyncCollectionResponse.ChangesRequired] = [
            .noChanges,
            .normalSync,
            .fullSync,
            .fullDownload,
            .fullUpload,
        ]
    }

    init() {}

    fileprivate var _newEndpoint: String?
}

struct Anki_Sync_MediaSyncStatusResponse {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var active: Bool = false

    var progress: Anki_Sync_MediaSyncProgress {
        get { _progress ?? Anki_Sync_MediaSyncProgress() }
        set { _progress = newValue }
    }

    /// Returns true if `progress` has been explicitly set.
    var hasProgress: Bool {
        _progress != nil
    }

    /// Clears the value of `progress`. Subsequent reads from it will return its default value.
    mutating func clearProgress() {
        _progress = nil
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    private var _progress: Anki_Sync_MediaSyncProgress?
}

struct Anki_Sync_MediaSyncProgress {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var checked: String = .init()

    var added: String = .init()

    var removed: String = .init()

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Anki_Sync_FullUploadOrDownloadRequest {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var auth: Anki_Sync_SyncAuth {
        get { _auth ?? Anki_Sync_SyncAuth() }
        set { _auth = newValue }
    }

    /// Returns true if `auth` has been explicitly set.
    var hasAuth: Bool {
        _auth != nil
    }

    /// Clears the value of `auth`. Subsequent reads from it will return its default value.
    mutating func clearAuth() {
        _auth = nil
    }

    var upload: Bool = false

    /// if not provided, media syncing will be skipped
    var serverUsn: Int32 {
        get { _serverUsn ?? 0 }
        set { _serverUsn = newValue }
    }

    /// Returns true if `serverUsn` has been explicitly set.
    var hasServerUsn: Bool {
        _serverUsn != nil
    }

    /// Clears the value of `serverUsn`. Subsequent reads from it will return its default value.
    mutating func clearServerUsn() {
        _serverUsn = nil
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _auth: Anki_Sync_SyncAuth?
    private var _serverUsn: Int32?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "anki.sync"

extension Anki_Sync_SyncAuth: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".SyncAuth"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}hkey\0\u{1}endpoint\0\u{3}io_timeout_secs\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &hkey)
                case 2: try decoder.decodeSingularStringField(value: &_endpoint)
                case 3: try decoder.decodeSingularUInt32Field(value: &_ioTimeoutSecs)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !hkey.isEmpty {
            try visitor.visitSingularStringField(value: hkey, fieldNumber: 1)
        }
        try { if let v = self._endpoint {
            try visitor.visitSingularStringField(value: v, fieldNumber: 2)
        } }()
        try { if let v = self._ioTimeoutSecs {
            try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Sync_SyncAuth, rhs: Anki_Sync_SyncAuth) -> Bool {
        if lhs.hkey != rhs.hkey { return false }
        if lhs._endpoint != rhs._endpoint { return false }
        if lhs._ioTimeoutSecs != rhs._ioTimeoutSecs { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Sync_SyncLoginRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".SyncLoginRequest"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}username\0\u{1}password\0\u{1}endpoint\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &username)
                case 2: try decoder.decodeSingularStringField(value: &password)
                case 3: try decoder.decodeSingularStringField(value: &_endpoint)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !username.isEmpty {
            try visitor.visitSingularStringField(value: username, fieldNumber: 1)
        }
        if !password.isEmpty {
            try visitor.visitSingularStringField(value: password, fieldNumber: 2)
        }
        try { if let v = self._endpoint {
            try visitor.visitSingularStringField(value: v, fieldNumber: 3)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Sync_SyncLoginRequest, rhs: Anki_Sync_SyncLoginRequest) -> Bool {
        if lhs.username != rhs.username { return false }
        if lhs.password != rhs.password { return false }
        if lhs._endpoint != rhs._endpoint { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Sync_SyncStatusResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".SyncStatusResponse"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}required\0\u{4}\u{3}new_endpoint\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularEnumField(value: &required)
                case 4: try decoder.decodeSingularStringField(value: &_newEndpoint)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if required != .noChanges {
            try visitor.visitSingularEnumField(value: required, fieldNumber: 1)
        }
        try { if let v = self._newEndpoint {
            try visitor.visitSingularStringField(value: v, fieldNumber: 4)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Sync_SyncStatusResponse, rhs: Anki_Sync_SyncStatusResponse) -> Bool {
        if lhs.required != rhs.required { return false }
        if lhs._newEndpoint != rhs._newEndpoint { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Sync_SyncStatusResponse.Required: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{2}\0NO_CHANGES\0\u{1}NORMAL_SYNC\0\u{1}FULL_SYNC\0")
}

extension Anki_Sync_SyncCollectionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".SyncCollectionRequest"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}auth\0\u{3}sync_media\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_auth)
                case 2: try decoder.decodeSingularBoolField(value: &syncMedia)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _auth {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if syncMedia != false {
            try visitor.visitSingularBoolField(value: syncMedia, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Sync_SyncCollectionRequest, rhs: Anki_Sync_SyncCollectionRequest) -> Bool {
        if lhs._auth != rhs._auth { return false }
        if lhs.syncMedia != rhs.syncMedia { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Sync_SyncCollectionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".SyncCollectionResponse"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{3}host_number\0\u{3}server_message\0\u{1}required\0\u{3}new_endpoint\0\u{3}server_media_usn\0"
        )

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularUInt32Field(value: &hostNumber)
                case 2: try decoder.decodeSingularStringField(value: &serverMessage)
                case 3: try decoder.decodeSingularEnumField(value: &required)
                case 4: try decoder.decodeSingularStringField(value: &_newEndpoint)
                case 5: try decoder.decodeSingularInt32Field(value: &serverMediaUsn)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if hostNumber != 0 {
            try visitor.visitSingularUInt32Field(value: hostNumber, fieldNumber: 1)
        }
        if !serverMessage.isEmpty {
            try visitor.visitSingularStringField(value: serverMessage, fieldNumber: 2)
        }
        if required != .noChanges {
            try visitor.visitSingularEnumField(value: required, fieldNumber: 3)
        }
        try { if let v = self._newEndpoint {
            try visitor.visitSingularStringField(value: v, fieldNumber: 4)
        } }()
        if serverMediaUsn != 0 {
            try visitor.visitSingularInt32Field(value: serverMediaUsn, fieldNumber: 5)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Sync_SyncCollectionResponse, rhs: Anki_Sync_SyncCollectionResponse) -> Bool {
        if lhs.hostNumber != rhs.hostNumber { return false }
        if lhs.serverMessage != rhs.serverMessage { return false }
        if lhs.required != rhs.required { return false }
        if lhs._newEndpoint != rhs._newEndpoint { return false }
        if lhs.serverMediaUsn != rhs.serverMediaUsn { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Sync_SyncCollectionResponse.ChangesRequired: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{2}\0NO_CHANGES\0\u{1}NORMAL_SYNC\0\u{1}FULL_SYNC\0\u{1}FULL_DOWNLOAD\0\u{1}FULL_UPLOAD\0"
        )
}

extension Anki_Sync_MediaSyncStatusResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".MediaSyncStatusResponse"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}active\0\u{1}progress\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularBoolField(value: &active)
                case 2: try decoder.decodeSingularMessageField(value: &_progress)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if active != false {
            try visitor.visitSingularBoolField(value: active, fieldNumber: 1)
        }
        try { if let v = self._progress {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Sync_MediaSyncStatusResponse, rhs: Anki_Sync_MediaSyncStatusResponse) -> Bool {
        if lhs.active != rhs.active { return false }
        if lhs._progress != rhs._progress { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Sync_MediaSyncProgress: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".MediaSyncProgress"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}checked\0\u{1}added\0\u{1}removed\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &checked)
                case 2: try decoder.decodeSingularStringField(value: &added)
                case 3: try decoder.decodeSingularStringField(value: &removed)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !checked.isEmpty {
            try visitor.visitSingularStringField(value: checked, fieldNumber: 1)
        }
        if !added.isEmpty {
            try visitor.visitSingularStringField(value: added, fieldNumber: 2)
        }
        if !removed.isEmpty {
            try visitor.visitSingularStringField(value: removed, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Sync_MediaSyncProgress, rhs: Anki_Sync_MediaSyncProgress) -> Bool {
        if lhs.checked != rhs.checked { return false }
        if lhs.added != rhs.added { return false }
        if lhs.removed != rhs.removed { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Sync_FullUploadOrDownloadRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".FullUploadOrDownloadRequest"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}auth\0\u{1}upload\0\u{3}server_usn\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_auth)
                case 2: try decoder.decodeSingularBoolField(value: &upload)
                case 3: try decoder.decodeSingularInt32Field(value: &_serverUsn)
                default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _auth {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if upload != false {
            try visitor.visitSingularBoolField(value: upload, fieldNumber: 2)
        }
        try { if let v = self._serverUsn {
            try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Anki_Sync_FullUploadOrDownloadRequest, rhs: Anki_Sync_FullUploadOrDownloadRequest) -> Bool {
        if lhs._auth != rhs._auth { return false }
        if lhs.upload != rhs.upload { return false }
        if lhs._serverUsn != rhs._serverUsn { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
