// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/backend.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct Anki_Backend_BackendInit: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var preferredLangs: [String] = []

    public var localeFolderPath: String = .init()

    public var server: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Backend_I18nBackendInit: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var preferredLangs: [String] = []

    public var localeFolderPath: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Backend_BackendError: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// error description, usually localized, suitable for displaying to the user
    public var message: String = .init()

    /// the error subtype
    public var kind: Anki_Backend_BackendError.Kind = .invalidInput

    /// optional page in the manual
    public var helpPage: Anki_Links_HelpPageLinkRequest.HelpPage {
        get { _helpPage ?? .noteType }
        set { _helpPage = newValue }
    }

    /// Returns true if `helpPage` has been explicitly set.
    public var hasHelpPage: Bool {
        _helpPage != nil
    }

    /// Clears the value of `helpPage`. Subsequent reads from it will return its default value.
    public mutating func clearHelpPage() {
        _helpPage = nil
    }

    /// additional information about the context in which the error occurred
    public var context: String = .init()

    /// a backtrace of the underlying error; requires RUST_BACKTRACE to be set
    public var backtrace: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum Kind: SwiftProtobuf.Enum, Swift.CaseIterable {
        public typealias RawValue = Int
        case invalidInput // = 0
        case undoEmpty // = 1
        case interrupted // = 2
        case templateParse // = 3
        case ioError // = 4
        case dbError // = 5
        case networkError // = 6
        case syncAuthError // = 7
        case syncServerMessage // = 23
        case syncOtherError // = 8
        case jsonError // = 9
        case protoError // = 10
        case notFoundError // = 11
        case exists // = 12
        case filteredDeckError // = 13
        case searchError // = 14
        case customStudyError // = 15
        case importError // = 16
        case deleted // = 17
        case cardTypeError // = 18
        case ankidroidPanicError // = 19

        /// Originated from and usually specific to the OS.
        case osError // = 20
        case schedulerUpgradeRequired // = 21
        case invalidCertificateFormat // = 22
        case UNRECOGNIZED(Int)

        public init() {
            self = .invalidInput
        }

        public init?(rawValue: Int) {
            switch rawValue {
                case 0: self = .invalidInput
                case 1: self = .undoEmpty
                case 2: self = .interrupted
                case 3: self = .templateParse
                case 4: self = .ioError
                case 5: self = .dbError
                case 6: self = .networkError
                case 7: self = .syncAuthError
                case 8: self = .syncOtherError
                case 9: self = .jsonError
                case 10: self = .protoError
                case 11: self = .notFoundError
                case 12: self = .exists
                case 13: self = .filteredDeckError
                case 14: self = .searchError
                case 15: self = .customStudyError
                case 16: self = .importError
                case 17: self = .deleted
                case 18: self = .cardTypeError
                case 19: self = .ankidroidPanicError
                case 20: self = .osError
                case 21: self = .schedulerUpgradeRequired
                case 22: self = .invalidCertificateFormat
                case 23: self = .syncServerMessage
                default: self = .UNRECOGNIZED(rawValue)
            }
        }

        public var rawValue: Int {
            switch self {
                case .invalidInput: 0
                case .undoEmpty: 1
                case .interrupted: 2
                case .templateParse: 3
                case .ioError: 4
                case .dbError: 5
                case .networkError: 6
                case .syncAuthError: 7
                case .syncOtherError: 8
                case .jsonError: 9
                case .protoError: 10
                case .notFoundError: 11
                case .exists: 12
                case .filteredDeckError: 13
                case .searchError: 14
                case .customStudyError: 15
                case .importError: 16
                case .deleted: 17
                case .cardTypeError: 18
                case .ankidroidPanicError: 19
                case .osError: 20
                case .schedulerUpgradeRequired: 21
                case .invalidCertificateFormat: 22
                case .syncServerMessage: 23
                case let .UNRECOGNIZED(i): i
            }
        }

        /// The compiler won't synthesize support with the UNRECOGNIZED case.
        public static let allCases: [Anki_Backend_BackendError.Kind] = [
            .invalidInput,
            .undoEmpty,
            .interrupted,
            .templateParse,
            .ioError,
            .dbError,
            .networkError,
            .syncAuthError,
            .syncServerMessage,
            .syncOtherError,
            .jsonError,
            .protoError,
            .notFoundError,
            .exists,
            .filteredDeckError,
            .searchError,
            .customStudyError,
            .importError,
            .deleted,
            .cardTypeError,
            .ankidroidPanicError,
            .osError,
            .schedulerUpgradeRequired,
            .invalidCertificateFormat,
        ]
    }

    public init() {}

    fileprivate var _helpPage: Anki_Links_HelpPageLinkRequest.HelpPage?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "anki.backend"

extension Anki_Backend_BackendInit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".BackendInit"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}preferred_langs\0\u{3}locale_folder_path\0\u{1}server\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedStringField(value: &preferredLangs)
                case 2: try decoder.decodeSingularStringField(value: &localeFolderPath)
                case 3: try decoder.decodeSingularBoolField(value: &server)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !preferredLangs.isEmpty {
            try visitor.visitRepeatedStringField(value: preferredLangs, fieldNumber: 1)
        }
        if !localeFolderPath.isEmpty {
            try visitor.visitSingularStringField(value: localeFolderPath, fieldNumber: 2)
        }
        if server != false {
            try visitor.visitSingularBoolField(value: server, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Backend_BackendInit, rhs: Anki_Backend_BackendInit) -> Bool {
        if lhs.preferredLangs != rhs.preferredLangs { return false }
        if lhs.localeFolderPath != rhs.localeFolderPath { return false }
        if lhs.server != rhs.server { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Backend_I18nBackendInit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".I18nBackendInit"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{4}\u{4}preferred_langs\0\u{3}locale_folder_path\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 4: try decoder.decodeRepeatedStringField(value: &preferredLangs)
                case 5: try decoder.decodeSingularStringField(value: &localeFolderPath)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !preferredLangs.isEmpty {
            try visitor.visitRepeatedStringField(value: preferredLangs, fieldNumber: 4)
        }
        if !localeFolderPath.isEmpty {
            try visitor.visitSingularStringField(value: localeFolderPath, fieldNumber: 5)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Backend_I18nBackendInit, rhs: Anki_Backend_I18nBackendInit) -> Bool {
        if lhs.preferredLangs != rhs.preferredLangs { return false }
        if lhs.localeFolderPath != rhs.localeFolderPath { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Backend_BackendError: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".BackendError"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}message\0\u{1}kind\0\u{3}help_page\0\u{1}context\0\u{1}backtrace\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &message)
                case 2: try decoder.decodeSingularEnumField(value: &kind)
                case 3: try decoder.decodeSingularEnumField(value: &_helpPage)
                case 4: try decoder.decodeSingularStringField(value: &context)
                case 5: try decoder.decodeSingularStringField(value: &backtrace)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !message.isEmpty {
            try visitor.visitSingularStringField(value: message, fieldNumber: 1)
        }
        if kind != .invalidInput {
            try visitor.visitSingularEnumField(value: kind, fieldNumber: 2)
        }
        try { if let v = self._helpPage {
            try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
        } }()
        if !context.isEmpty {
            try visitor.visitSingularStringField(value: context, fieldNumber: 4)
        }
        if !backtrace.isEmpty {
            try visitor.visitSingularStringField(value: backtrace, fieldNumber: 5)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Backend_BackendError, rhs: Anki_Backend_BackendError) -> Bool {
        if lhs.message != rhs.message { return false }
        if lhs.kind != rhs.kind { return false }
        if lhs._helpPage != rhs._helpPage { return false }
        if lhs.context != rhs.context { return false }
        if lhs.backtrace != rhs.backtrace { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Backend_BackendError.Kind: SwiftProtobuf._ProtoNameProviding {
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{2}\0INVALID_INPUT\0\u{1}UNDO_EMPTY\0\u{1}INTERRUPTED\0\u{1}TEMPLATE_PARSE\0\u{1}IO_ERROR\0\u{1}DB_ERROR\0\u{1}NETWORK_ERROR\0\u{1}SYNC_AUTH_ERROR\0\u{1}SYNC_OTHER_ERROR\0\u{1}JSON_ERROR\0\u{1}PROTO_ERROR\0\u{1}NOT_FOUND_ERROR\0\u{1}EXISTS\0\u{1}FILTERED_DECK_ERROR\0\u{1}SEARCH_ERROR\0\u{1}CUSTOM_STUDY_ERROR\0\u{1}IMPORT_ERROR\0\u{1}DELETED\0\u{1}CARD_TYPE_ERROR\0\u{1}ANKIDROID_PANIC_ERROR\0\u{1}OS_ERROR\0\u{1}SCHEDULER_UPGRADE_REQUIRED\0\u{1}INVALID_CERTIFICATE_FORMAT\0\u{1}SYNC_SERVER_MESSAGE\0"
        )
}
