// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/card_rendering.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

#if canImport(FoundationEssentials)
    import FoundationEssentials
#else
    import Foundation
#endif
import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct Anki_CardRendering_ExtractAvTagsRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var text: String = .init()

    public var questionSide: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_CardRendering_ExtractAvTagsResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var text: String = .init()

    public var avTags: [Anki_CardRendering_AVTag] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_CardRendering_AVTag: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var value: Anki_CardRendering_AVTag.OneOf_Value?

    public var soundOrVideo: String {
        get {
            if case let .soundOrVideo(v)? = value { return v }
            return String()
        }
        set { value = .soundOrVideo(newValue) }
    }

    public var tts: Anki_CardRendering_TTSTag {
        get {
            if case let .tts(v)? = value { return v }
            return Anki_CardRendering_TTSTag()
        }
        set { value = .tts(newValue) }
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum OneOf_Value: Equatable, Sendable {
        case soundOrVideo(String)
        case tts(Anki_CardRendering_TTSTag)
    }

    public init() {}
}

public struct Anki_CardRendering_TTSTag: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var fieldText: String = .init()

    public var lang: String = .init()

    public var voices: [String] = []

    public var speed: Float = 0

    public var otherArgs: [String] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_CardRendering_ExtractLatexRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var text: String = .init()

    public var svg: Bool = false

    public var expandClozes: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_CardRendering_ExtractLatexResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var text: String = .init()

    public var latex: [Anki_CardRendering_ExtractedLatex] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_CardRendering_ExtractedLatex: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var filename: String = .init()

    public var latexBody: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_CardRendering_EmptyCardsReport: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var report: String = .init()

    public var notes: [Anki_CardRendering_EmptyCardsReport.NoteWithEmptyCards] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public struct NoteWithEmptyCards: Sendable {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        public var noteID: Int64 = 0

        public var cardIds: [Int64] = []

        public var willDeleteNote: Bool = false

        public var unknownFields = SwiftProtobuf.UnknownStorage()

        public init() {}
    }

    public init() {}
}

public struct Anki_CardRendering_RenderExistingCardRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var cardID: Int64 = 0

    public var browser: Bool = false

    /// If true, rendering will stop when an unknown filter is encountered,
    /// and caller will need to complete rendering. This is done to allow
    /// Python code to modify the rendering.
    public var partialRender: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_CardRendering_RenderUncommittedCardRequest: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var note: Anki_Notes_Note {
        get { _storage._note ?? Anki_Notes_Note() }
        set { _uniqueStorage()._note = newValue }
    }

    /// Returns true if `note` has been explicitly set.
    public var hasNote: Bool {
        _storage._note != nil
    }

    /// Clears the value of `note`. Subsequent reads from it will return its default value.
    public mutating func clearNote() {
        _uniqueStorage()._note = nil
    }

    public var cardOrd: UInt32 {
        get { _storage._cardOrd }
        set { _uniqueStorage()._cardOrd = newValue }
    }

    public var template: Anki_Notetypes_Notetype.Template {
        get { _storage._template ?? Anki_Notetypes_Notetype.Template() }
        set { _uniqueStorage()._template = newValue }
    }

    /// Returns true if `template` has been explicitly set.
    public var hasTemplate: Bool {
        _storage._template != nil
    }

    /// Clears the value of `template`. Subsequent reads from it will return its default value.
    public mutating func clearTemplate() {
        _uniqueStorage()._template = nil
    }

    public var fillEmpty: Bool {
        get { _storage._fillEmpty }
        set { _uniqueStorage()._fillEmpty = newValue }
    }

    /// If true, rendering will stop when an unknown filter is encountered,
    /// and caller will need to complete rendering. This is done to allow
    /// Python code to modify the rendering.
    public var partialRender: Bool {
        get { _storage._partialRender }
        set { _uniqueStorage()._partialRender = newValue }
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Anki_CardRendering_RenderUncommittedCardLegacyRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var note: Anki_Notes_Note {
        get { _note ?? Anki_Notes_Note() }
        set { _note = newValue }
    }

    /// Returns true if `note` has been explicitly set.
    public var hasNote: Bool {
        _note != nil
    }

    /// Clears the value of `note`. Subsequent reads from it will return its default value.
    public mutating func clearNote() {
        _note = nil
    }

    public var cardOrd: UInt32 = 0

    public var template: Data = .init()

    public var fillEmpty: Bool = false

    /// If true, rendering will stop when an unknown filter is encountered,
    /// and caller will need to complete rendering. This is done to allow
    /// Python code to modify the rendering.
    public var partialRender: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _note: Anki_Notes_Note?
}

public struct Anki_CardRendering_RenderCardResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var questionNodes: [Anki_CardRendering_RenderedTemplateNode] = []

    public var answerNodes: [Anki_CardRendering_RenderedTemplateNode] = []

    public var css: String = .init()

    public var latexSvg: Bool = false

    public var isEmpty: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_CardRendering_RenderedTemplateNode: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var value: Anki_CardRendering_RenderedTemplateNode.OneOf_Value?

    public var text: String {
        get {
            if case let .text(v)? = value { return v }
            return String()
        }
        set { value = .text(newValue) }
    }

    public var replacement: Anki_CardRendering_RenderedTemplateReplacement {
        get {
            if case let .replacement(v)? = value { return v }
            return Anki_CardRendering_RenderedTemplateReplacement()
        }
        set { value = .replacement(newValue) }
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum OneOf_Value: Equatable, Sendable {
        case text(String)
        case replacement(Anki_CardRendering_RenderedTemplateReplacement)
    }

    public init() {}
}

public struct Anki_CardRendering_RenderedTemplateReplacement: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var fieldName: String = .init()

    public var currentText: String = .init()

    public var filters: [String] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_CardRendering_RenderMarkdownRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var markdown: String = .init()

    public var sanitize: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_CardRendering_StripHtmlRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var text: String = .init()

    public var mode: Anki_CardRendering_StripHtmlRequest.Mode = .normal

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum Mode: SwiftProtobuf.Enum, Swift.CaseIterable {
        public typealias RawValue = Int
        case normal // = 0
        case preserveMediaFilenames // = 1
        case UNRECOGNIZED(Int)

        public init() {
            self = .normal
        }

        public init?(rawValue: Int) {
            switch rawValue {
                case 0: self = .normal
                case 1: self = .preserveMediaFilenames
                default: self = .UNRECOGNIZED(rawValue)
            }
        }

        public var rawValue: Int {
            switch self {
                case .normal: 0
                case .preserveMediaFilenames: 1
                case let .UNRECOGNIZED(i): i
            }
        }

        /// The compiler won't synthesize support with the UNRECOGNIZED case.
        public static let allCases: [Anki_CardRendering_StripHtmlRequest.Mode] = [
            .normal,
            .preserveMediaFilenames,
        ]
    }

    public init() {}
}

public struct Anki_CardRendering_HtmlToTextLineRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var text: String = .init()

    public var preserveMediaFilenames: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_CardRendering_CompareAnswerRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var expected: String = .init()

    public var provided: String = .init()

    public var combining: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_CardRendering_ExtractClozeForTypingRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var text: String = .init()

    public var ordinal: UInt32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_CardRendering_AllTtsVoicesRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var validate: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_CardRendering_AllTtsVoicesResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var voices: [Anki_CardRendering_AllTtsVoicesResponse.TtsVoice] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public struct TtsVoice: Sendable {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        public var id: String = .init()

        public var name: String = .init()

        public var language: String = .init()

        public var available: Bool {
            get { _available ?? false }
            set { _available = newValue }
        }

        /// Returns true if `available` has been explicitly set.
        public var hasAvailable: Bool {
            _available != nil
        }

        /// Clears the value of `available`. Subsequent reads from it will return its default value.
        public mutating func clearAvailable() {
            _available = nil
        }

        public var unknownFields = SwiftProtobuf.UnknownStorage()

        public init() {}

        fileprivate var _available: Bool?
    }

    public init() {}
}

public struct Anki_CardRendering_WriteTtsStreamRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var path: String = .init()

    public var voiceID: String = .init()

    public var speed: Float = 0

    public var text: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "anki.card_rendering"

extension Anki_CardRendering_ExtractAvTagsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ExtractAvTagsRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{3}question_side\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &text)
                case 2: try decoder.decodeSingularBoolField(value: &questionSide)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !text.isEmpty {
            try visitor.visitSingularStringField(value: text, fieldNumber: 1)
        }
        if questionSide != false {
            try visitor.visitSingularBoolField(value: questionSide, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_ExtractAvTagsRequest,
                           rhs: Anki_CardRendering_ExtractAvTagsRequest) -> Bool {
        if lhs.text != rhs.text { return false }
        if lhs.questionSide != rhs.questionSide { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_ExtractAvTagsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ExtractAvTagsResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{3}av_tags\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &text)
                case 2: try decoder.decodeRepeatedMessageField(value: &avTags)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !text.isEmpty {
            try visitor.visitSingularStringField(value: text, fieldNumber: 1)
        }
        if !avTags.isEmpty {
            try visitor.visitRepeatedMessageField(value: avTags, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_ExtractAvTagsResponse,
                           rhs: Anki_CardRendering_ExtractAvTagsResponse) -> Bool {
        if lhs.text != rhs.text { return false }
        if lhs.avTags != rhs.avTags { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_AVTag: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".AVTag"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}sound_or_video\0\u{1}tts\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try {
                        var v: String?
                        try decoder.decodeSingularStringField(value: &v)
                        if let v {
                            if self.value != nil { try decoder.handleConflictingOneOf() }
                            self.value = .soundOrVideo(v)
                        }
                    }()
                case 2: try {
                        var v: Anki_CardRendering_TTSTag?
                        var hadOneofValue = false
                        if let current = self.value {
                            hadOneofValue = true
                            if case let .tts(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.value = .tts(v)
                        }
                    }()
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        switch value {
            case .soundOrVideo?: try {
                    guard case let .soundOrVideo(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularStringField(value: v, fieldNumber: 1)
                }()
            case .tts?: try {
                    guard case let .tts(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
                }()
            case nil: break
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_AVTag, rhs: Anki_CardRendering_AVTag) -> Bool {
        if lhs.value != rhs.value { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_TTSTag: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".TTSTag"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}field_text\0\u{1}lang\0\u{1}voices\0\u{1}speed\0\u{3}other_args\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &fieldText)
                case 2: try decoder.decodeSingularStringField(value: &lang)
                case 3: try decoder.decodeRepeatedStringField(value: &voices)
                case 4: try decoder.decodeSingularFloatField(value: &speed)
                case 5: try decoder.decodeRepeatedStringField(value: &otherArgs)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !fieldText.isEmpty {
            try visitor.visitSingularStringField(value: fieldText, fieldNumber: 1)
        }
        if !lang.isEmpty {
            try visitor.visitSingularStringField(value: lang, fieldNumber: 2)
        }
        if !voices.isEmpty {
            try visitor.visitRepeatedStringField(value: voices, fieldNumber: 3)
        }
        if speed.bitPattern != 0 {
            try visitor.visitSingularFloatField(value: speed, fieldNumber: 4)
        }
        if !otherArgs.isEmpty {
            try visitor.visitRepeatedStringField(value: otherArgs, fieldNumber: 5)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_TTSTag, rhs: Anki_CardRendering_TTSTag) -> Bool {
        if lhs.fieldText != rhs.fieldText { return false }
        if lhs.lang != rhs.lang { return false }
        if lhs.voices != rhs.voices { return false }
        if lhs.speed != rhs.speed { return false }
        if lhs.otherArgs != rhs.otherArgs { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_ExtractLatexRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ExtractLatexRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}text\0\u{1}svg\0\u{3}expand_clozes\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &text)
                case 2: try decoder.decodeSingularBoolField(value: &svg)
                case 3: try decoder.decodeSingularBoolField(value: &expandClozes)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !text.isEmpty {
            try visitor.visitSingularStringField(value: text, fieldNumber: 1)
        }
        if svg != false {
            try visitor.visitSingularBoolField(value: svg, fieldNumber: 2)
        }
        if expandClozes != false {
            try visitor.visitSingularBoolField(value: expandClozes, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_ExtractLatexRequest,
                           rhs: Anki_CardRendering_ExtractLatexRequest) -> Bool {
        if lhs.text != rhs.text { return false }
        if lhs.svg != rhs.svg { return false }
        if lhs.expandClozes != rhs.expandClozes { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_ExtractLatexResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ExtractLatexResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{1}latex\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &text)
                case 2: try decoder.decodeRepeatedMessageField(value: &latex)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !text.isEmpty {
            try visitor.visitSingularStringField(value: text, fieldNumber: 1)
        }
        if !latex.isEmpty {
            try visitor.visitRepeatedMessageField(value: latex, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_ExtractLatexResponse,
                           rhs: Anki_CardRendering_ExtractLatexResponse) -> Bool {
        if lhs.text != rhs.text { return false }
        if lhs.latex != rhs.latex { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_ExtractedLatex: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ExtractedLatex"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}filename\0\u{3}latex_body\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &filename)
                case 2: try decoder.decodeSingularStringField(value: &latexBody)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !filename.isEmpty {
            try visitor.visitSingularStringField(value: filename, fieldNumber: 1)
        }
        if !latexBody.isEmpty {
            try visitor.visitSingularStringField(value: latexBody, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_ExtractedLatex, rhs: Anki_CardRendering_ExtractedLatex) -> Bool {
        if lhs.filename != rhs.filename { return false }
        if lhs.latexBody != rhs.latexBody { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_EmptyCardsReport: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".EmptyCardsReport"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}report\0\u{1}notes\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &report)
                case 2: try decoder.decodeRepeatedMessageField(value: &notes)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !report.isEmpty {
            try visitor.visitSingularStringField(value: report, fieldNumber: 1)
        }
        if !notes.isEmpty {
            try visitor.visitRepeatedMessageField(value: notes, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_EmptyCardsReport, rhs: Anki_CardRendering_EmptyCardsReport) -> Bool {
        if lhs.report != rhs.report { return false }
        if lhs.notes != rhs.notes { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_EmptyCardsReport.NoteWithEmptyCards: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = Anki_CardRendering_EmptyCardsReport.protoMessageName + ".NoteWithEmptyCards"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}note_id\0\u{3}card_ids\0\u{3}will_delete_note\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularInt64Field(value: &noteID)
                case 2: try decoder.decodeRepeatedInt64Field(value: &cardIds)
                case 3: try decoder.decodeSingularBoolField(value: &willDeleteNote)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if noteID != 0 {
            try visitor.visitSingularInt64Field(value: noteID, fieldNumber: 1)
        }
        if !cardIds.isEmpty {
            try visitor.visitPackedInt64Field(value: cardIds, fieldNumber: 2)
        }
        if willDeleteNote != false {
            try visitor.visitSingularBoolField(value: willDeleteNote, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_CardRendering_EmptyCardsReport.NoteWithEmptyCards,
        rhs: Anki_CardRendering_EmptyCardsReport.NoteWithEmptyCards
    ) -> Bool {
        if lhs.noteID != rhs.noteID { return false }
        if lhs.cardIds != rhs.cardIds { return false }
        if lhs.willDeleteNote != rhs.willDeleteNote { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_RenderExistingCardRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".RenderExistingCardRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}card_id\0\u{1}browser\0\u{3}partial_render\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularInt64Field(value: &cardID)
                case 2: try decoder.decodeSingularBoolField(value: &browser)
                case 3: try decoder.decodeSingularBoolField(value: &partialRender)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if cardID != 0 {
            try visitor.visitSingularInt64Field(value: cardID, fieldNumber: 1)
        }
        if browser != false {
            try visitor.visitSingularBoolField(value: browser, fieldNumber: 2)
        }
        if partialRender != false {
            try visitor.visitSingularBoolField(value: partialRender, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_CardRendering_RenderExistingCardRequest,
        rhs: Anki_CardRendering_RenderExistingCardRequest
    ) -> Bool {
        if lhs.cardID != rhs.cardID { return false }
        if lhs.browser != rhs.browser { return false }
        if lhs.partialRender != rhs.partialRender { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_RenderUncommittedCardRequest: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".RenderUncommittedCardRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}note\0\u{3}card_ord\0\u{1}template\0\u{3}fill_empty\0\u{3}partial_render\0")

    fileprivate class _StorageClass {
        var _note: Anki_Notes_Note?
        var _cardOrd: UInt32 = 0
        var _template: Anki_Notetypes_Notetype.Template?
        var _fillEmpty: Bool = false
        var _partialRender: Bool = false

        /// This property is used as the initial default value for new instances of the type.
        /// The type itself is protecting the reference to its storage via CoW semantics.
        /// This will force a copy to be made of this reference when the first mutation occurs;
        /// hence, it is safe to mark this as `nonisolated(unsafe)`.
        nonisolated(unsafe) static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            _note = source._note
            _cardOrd = source._cardOrd
            _template = source._template
            _fillEmpty = source._fillEmpty
            _partialRender = source._partialRender
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&_storage) {
            _storage = _StorageClass(copying: _storage)
        }
        return _storage
    }

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        _ = _uniqueStorage()
        try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                // The use of inline closures is to circumvent an issue where the compiler
                // allocates stack space for every case branch when no optimizations are
                // enabled. https://github.com/apple/swift-protobuf/issues/1034
                switch fieldNumber {
                    case 1: try decoder.decodeSingularMessageField(value: &_storage._note)
                    case 2: try decoder.decodeSingularUInt32Field(value: &_storage._cardOrd)
                    case 3: try decoder.decodeSingularMessageField(value: &_storage._template)
                    case 4: try decoder.decodeSingularBoolField(value: &_storage._fillEmpty)
                    case 5: try decoder.decodeSingularBoolField(value: &_storage._partialRender)
                    default: break
                }
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every if/case branch local when no optimizations
            // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
            // https://github.com/apple/swift-protobuf/issues/1182
            try { if let v = _storage._note {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
            } }()
            if _storage._cardOrd != 0 {
                try visitor.visitSingularUInt32Field(value: _storage._cardOrd, fieldNumber: 2)
            }
            try { if let v = _storage._template {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
            } }()
            if _storage._fillEmpty != false {
                try visitor.visitSingularBoolField(value: _storage._fillEmpty, fieldNumber: 4)
            }
            if _storage._partialRender != false {
                try visitor.visitSingularBoolField(value: _storage._partialRender, fieldNumber: 5)
            }
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_CardRendering_RenderUncommittedCardRequest,
        rhs: Anki_CardRendering_RenderUncommittedCardRequest
    ) -> Bool {
        if lhs._storage !== rhs._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((
                lhs._storage,
                rhs._storage
            )) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let rhs_storage = _args.1
                if _storage._note != rhs_storage._note { return false }
                if _storage._cardOrd != rhs_storage._cardOrd { return false }
                if _storage._template != rhs_storage._template { return false }
                if _storage._fillEmpty != rhs_storage._fillEmpty { return false }
                if _storage._partialRender != rhs_storage._partialRender { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_RenderUncommittedCardLegacyRequest: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".RenderUncommittedCardLegacyRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}note\0\u{3}card_ord\0\u{1}template\0\u{3}fill_empty\0\u{3}partial_render\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_note)
                case 2: try decoder.decodeSingularUInt32Field(value: &cardOrd)
                case 3: try decoder.decodeSingularBytesField(value: &template)
                case 4: try decoder.decodeSingularBoolField(value: &fillEmpty)
                case 5: try decoder.decodeSingularBoolField(value: &partialRender)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _note {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if cardOrd != 0 {
            try visitor.visitSingularUInt32Field(value: cardOrd, fieldNumber: 2)
        }
        if !template.isEmpty {
            try visitor.visitSingularBytesField(value: template, fieldNumber: 3)
        }
        if fillEmpty != false {
            try visitor.visitSingularBoolField(value: fillEmpty, fieldNumber: 4)
        }
        if partialRender != false {
            try visitor.visitSingularBoolField(value: partialRender, fieldNumber: 5)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_CardRendering_RenderUncommittedCardLegacyRequest,
        rhs: Anki_CardRendering_RenderUncommittedCardLegacyRequest
    ) -> Bool {
        if lhs._note != rhs._note { return false }
        if lhs.cardOrd != rhs.cardOrd { return false }
        if lhs.template != rhs.template { return false }
        if lhs.fillEmpty != rhs.fillEmpty { return false }
        if lhs.partialRender != rhs.partialRender { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_RenderCardResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".RenderCardResponse"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}question_nodes\0\u{3}answer_nodes\0\u{1}css\0\u{3}latex_svg\0\u{3}is_empty\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedMessageField(value: &questionNodes)
                case 2: try decoder.decodeRepeatedMessageField(value: &answerNodes)
                case 3: try decoder.decodeSingularStringField(value: &css)
                case 4: try decoder.decodeSingularBoolField(value: &latexSvg)
                case 5: try decoder.decodeSingularBoolField(value: &isEmpty)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !questionNodes.isEmpty {
            try visitor.visitRepeatedMessageField(value: questionNodes, fieldNumber: 1)
        }
        if !answerNodes.isEmpty {
            try visitor.visitRepeatedMessageField(value: answerNodes, fieldNumber: 2)
        }
        if !css.isEmpty {
            try visitor.visitSingularStringField(value: css, fieldNumber: 3)
        }
        if latexSvg != false {
            try visitor.visitSingularBoolField(value: latexSvg, fieldNumber: 4)
        }
        if isEmpty != false {
            try visitor.visitSingularBoolField(value: isEmpty, fieldNumber: 5)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_RenderCardResponse,
                           rhs: Anki_CardRendering_RenderCardResponse) -> Bool {
        if lhs.questionNodes != rhs.questionNodes { return false }
        if lhs.answerNodes != rhs.answerNodes { return false }
        if lhs.css != rhs.css { return false }
        if lhs.latexSvg != rhs.latexSvg { return false }
        if lhs.isEmpty != rhs.isEmpty { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_RenderedTemplateNode: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".RenderedTemplateNode"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{1}replacement\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try {
                        var v: String?
                        try decoder.decodeSingularStringField(value: &v)
                        if let v {
                            if self.value != nil { try decoder.handleConflictingOneOf() }
                            self.value = .text(v)
                        }
                    }()
                case 2: try {
                        var v: Anki_CardRendering_RenderedTemplateReplacement?
                        var hadOneofValue = false
                        if let current = self.value {
                            hadOneofValue = true
                            if case let .replacement(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.value = .replacement(v)
                        }
                    }()
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        switch value {
            case .text?: try {
                    guard case let .text(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularStringField(value: v, fieldNumber: 1)
                }()
            case .replacement?: try {
                    guard case let .replacement(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
                }()
            case nil: break
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_RenderedTemplateNode,
                           rhs: Anki_CardRendering_RenderedTemplateNode) -> Bool {
        if lhs.value != rhs.value { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_RenderedTemplateReplacement: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".RenderedTemplateReplacement"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}field_name\0\u{3}current_text\0\u{1}filters\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &fieldName)
                case 2: try decoder.decodeSingularStringField(value: &currentText)
                case 3: try decoder.decodeRepeatedStringField(value: &filters)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !fieldName.isEmpty {
            try visitor.visitSingularStringField(value: fieldName, fieldNumber: 1)
        }
        if !currentText.isEmpty {
            try visitor.visitSingularStringField(value: currentText, fieldNumber: 2)
        }
        if !filters.isEmpty {
            try visitor.visitRepeatedStringField(value: filters, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_CardRendering_RenderedTemplateReplacement,
        rhs: Anki_CardRendering_RenderedTemplateReplacement
    ) -> Bool {
        if lhs.fieldName != rhs.fieldName { return false }
        if lhs.currentText != rhs.currentText { return false }
        if lhs.filters != rhs.filters { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_RenderMarkdownRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".RenderMarkdownRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}markdown\0\u{1}sanitize\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &markdown)
                case 2: try decoder.decodeSingularBoolField(value: &sanitize)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !markdown.isEmpty {
            try visitor.visitSingularStringField(value: markdown, fieldNumber: 1)
        }
        if sanitize != false {
            try visitor.visitSingularBoolField(value: sanitize, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_RenderMarkdownRequest,
                           rhs: Anki_CardRendering_RenderMarkdownRequest) -> Bool {
        if lhs.markdown != rhs.markdown { return false }
        if lhs.sanitize != rhs.sanitize { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_StripHtmlRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".StripHtmlRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{1}mode\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &text)
                case 2: try decoder.decodeSingularEnumField(value: &mode)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !text.isEmpty {
            try visitor.visitSingularStringField(value: text, fieldNumber: 1)
        }
        if mode != .normal {
            try visitor.visitSingularEnumField(value: mode, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_StripHtmlRequest, rhs: Anki_CardRendering_StripHtmlRequest) -> Bool {
        if lhs.text != rhs.text { return false }
        if lhs.mode != rhs.mode { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_StripHtmlRequest.Mode: SwiftProtobuf._ProtoNameProviding {
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{2}\0NORMAL\0\u{1}PRESERVE_MEDIA_FILENAMES\0")
}

extension Anki_CardRendering_HtmlToTextLineRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".HtmlToTextLineRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}text\0\u{3}preserve_media_filenames\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &text)
                case 2: try decoder.decodeSingularBoolField(value: &preserveMediaFilenames)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !text.isEmpty {
            try visitor.visitSingularStringField(value: text, fieldNumber: 1)
        }
        if preserveMediaFilenames != false {
            try visitor.visitSingularBoolField(value: preserveMediaFilenames, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_HtmlToTextLineRequest,
                           rhs: Anki_CardRendering_HtmlToTextLineRequest) -> Bool {
        if lhs.text != rhs.text { return false }
        if lhs.preserveMediaFilenames != rhs.preserveMediaFilenames { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_CompareAnswerRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".CompareAnswerRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}expected\0\u{1}provided\0\u{1}combining\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &expected)
                case 2: try decoder.decodeSingularStringField(value: &provided)
                case 3: try decoder.decodeSingularBoolField(value: &combining)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !expected.isEmpty {
            try visitor.visitSingularStringField(value: expected, fieldNumber: 1)
        }
        if !provided.isEmpty {
            try visitor.visitSingularStringField(value: provided, fieldNumber: 2)
        }
        if combining != false {
            try visitor.visitSingularBoolField(value: combining, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_CompareAnswerRequest,
                           rhs: Anki_CardRendering_CompareAnswerRequest) -> Bool {
        if lhs.expected != rhs.expected { return false }
        if lhs.provided != rhs.provided { return false }
        if lhs.combining != rhs.combining { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_ExtractClozeForTypingRequest: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ExtractClozeForTypingRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0\u{1}ordinal\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &text)
                case 2: try decoder.decodeSingularUInt32Field(value: &ordinal)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !text.isEmpty {
            try visitor.visitSingularStringField(value: text, fieldNumber: 1)
        }
        if ordinal != 0 {
            try visitor.visitSingularUInt32Field(value: ordinal, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_CardRendering_ExtractClozeForTypingRequest,
        rhs: Anki_CardRendering_ExtractClozeForTypingRequest
    ) -> Bool {
        if lhs.text != rhs.text { return false }
        if lhs.ordinal != rhs.ordinal { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_AllTtsVoicesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".AllTtsVoicesRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}validate\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularBoolField(value: &validate)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if validate != false {
            try visitor.visitSingularBoolField(value: validate, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_AllTtsVoicesRequest,
                           rhs: Anki_CardRendering_AllTtsVoicesRequest) -> Bool {
        if lhs.validate != rhs.validate { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_AllTtsVoicesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".AllTtsVoicesResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}voices\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedMessageField(value: &voices)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !voices.isEmpty {
            try visitor.visitRepeatedMessageField(value: voices, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_AllTtsVoicesResponse,
                           rhs: Anki_CardRendering_AllTtsVoicesResponse) -> Bool {
        if lhs.voices != rhs.voices { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_AllTtsVoicesResponse.TtsVoice: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = Anki_CardRendering_AllTtsVoicesResponse.protoMessageName + ".TtsVoice"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{1}language\0\u{1}available\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &id)
                case 2: try decoder.decodeSingularStringField(value: &name)
                case 3: try decoder.decodeSingularStringField(value: &language)
                case 4: try decoder.decodeSingularBoolField(value: &_available)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !id.isEmpty {
            try visitor.visitSingularStringField(value: id, fieldNumber: 1)
        }
        if !name.isEmpty {
            try visitor.visitSingularStringField(value: name, fieldNumber: 2)
        }
        if !language.isEmpty {
            try visitor.visitSingularStringField(value: language, fieldNumber: 3)
        }
        try { if let v = self._available {
            try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_CardRendering_AllTtsVoicesResponse.TtsVoice,
        rhs: Anki_CardRendering_AllTtsVoicesResponse.TtsVoice
    ) -> Bool {
        if lhs.id != rhs.id { return false }
        if lhs.name != rhs.name { return false }
        if lhs.language != rhs.language { return false }
        if lhs._available != rhs._available { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_CardRendering_WriteTtsStreamRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".WriteTtsStreamRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}path\0\u{3}voice_id\0\u{1}speed\0\u{1}text\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &path)
                case 2: try decoder.decodeSingularStringField(value: &voiceID)
                case 3: try decoder.decodeSingularFloatField(value: &speed)
                case 4: try decoder.decodeSingularStringField(value: &text)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !path.isEmpty {
            try visitor.visitSingularStringField(value: path, fieldNumber: 1)
        }
        if !voiceID.isEmpty {
            try visitor.visitSingularStringField(value: voiceID, fieldNumber: 2)
        }
        if speed.bitPattern != 0 {
            try visitor.visitSingularFloatField(value: speed, fieldNumber: 3)
        }
        if !text.isEmpty {
            try visitor.visitSingularStringField(value: text, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_CardRendering_WriteTtsStreamRequest,
                           rhs: Anki_CardRendering_WriteTtsStreamRequest) -> Bool {
        if lhs.path != rhs.path { return false }
        if lhs.voiceID != rhs.voiceID { return false }
        if lhs.speed != rhs.speed { return false }
        if lhs.text != rhs.text { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
