// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/collection.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct Anki_Collection_OpenCollectionRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var collectionPath: String = .init()

    public var mediaFolderPath: String = .init()

    public var mediaDbPath: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Collection_CloseCollectionRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var downgradeToSchema11: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Collection_CheckDatabaseResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var problems: [String] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Collection_OpChanges: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var card: Bool = false

    public var note: Bool = false

    public var deck: Bool = false

    public var tag: Bool = false

    public var notetype: Bool = false

    public var config: Bool = false

    public var deckConfig: Bool = false

    public var mtime: Bool = false

    public var browserTable: Bool = false

    public var browserSidebar: Bool = false

    /// editor and displayed card in review screen
    public var noteText: Bool = false

    /// whether to call .reset() and getCard()
    public var studyQueues: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

/// Allows frontend code to extract changes from other messages like
/// ImportResponse without decoding other potentially large fields.
public struct Anki_Collection_OpChangesOnly: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var changes: Anki_Collection_OpChanges {
        get { _changes ?? Anki_Collection_OpChanges() }
        set { _changes = newValue }
    }

    /// Returns true if `changes` has been explicitly set.
    public var hasChanges: Bool {
        _changes != nil
    }

    /// Clears the value of `changes`. Subsequent reads from it will return its default value.
    public mutating func clearChanges() {
        _changes = nil
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _changes: Anki_Collection_OpChanges?
}

public struct Anki_Collection_OpChangesWithCount: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var changes: Anki_Collection_OpChanges {
        get { _changes ?? Anki_Collection_OpChanges() }
        set { _changes = newValue }
    }

    /// Returns true if `changes` has been explicitly set.
    public var hasChanges: Bool {
        _changes != nil
    }

    /// Clears the value of `changes`. Subsequent reads from it will return its default value.
    public mutating func clearChanges() {
        _changes = nil
    }

    public var count: UInt32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _changes: Anki_Collection_OpChanges?
}

public struct Anki_Collection_OpChangesWithId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var changes: Anki_Collection_OpChanges {
        get { _changes ?? Anki_Collection_OpChanges() }
        set { _changes = newValue }
    }

    /// Returns true if `changes` has been explicitly set.
    public var hasChanges: Bool {
        _changes != nil
    }

    /// Clears the value of `changes`. Subsequent reads from it will return its default value.
    public mutating func clearChanges() {
        _changes = nil
    }

    public var id: Int64 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _changes: Anki_Collection_OpChanges?
}

public struct Anki_Collection_UndoStatus: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var undo: String = .init()

    public var redo: String = .init()

    public var lastStep: UInt32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Collection_OpChangesAfterUndo: @unchecked Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var changes: Anki_Collection_OpChanges {
        get { _storage._changes ?? Anki_Collection_OpChanges() }
        set { _uniqueStorage()._changes = newValue }
    }

    /// Returns true if `changes` has been explicitly set.
    public var hasChanges: Bool {
        _storage._changes != nil
    }

    /// Clears the value of `changes`. Subsequent reads from it will return its default value.
    public mutating func clearChanges() {
        _uniqueStorage()._changes = nil
    }

    public var operation: String {
        get { _storage._operation }
        set { _uniqueStorage()._operation = newValue }
    }

    public var revertedToTimestamp: Int64 {
        get { _storage._revertedToTimestamp }
        set { _uniqueStorage()._revertedToTimestamp = newValue }
    }

    public var newStatus: Anki_Collection_UndoStatus {
        get { _storage._newStatus ?? Anki_Collection_UndoStatus() }
        set { _uniqueStorage()._newStatus = newValue }
    }

    /// Returns true if `newStatus` has been explicitly set.
    public var hasNewStatus: Bool {
        _storage._newStatus != nil
    }

    /// Clears the value of `newStatus`. Subsequent reads from it will return its default value.
    public mutating func clearNewStatus() {
        _uniqueStorage()._newStatus = nil
    }

    public var counter: UInt32 {
        get { _storage._counter }
        set { _uniqueStorage()._counter = newValue }
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Anki_Collection_Progress: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var value: Anki_Collection_Progress.OneOf_Value?

    public var none: Anki_Generic_Empty {
        get {
            if case let .none(v)? = value { return v }
            return Anki_Generic_Empty()
        }
        set { value = .none(newValue) }
    }

    public var mediaSync: Anki_Sync_MediaSyncProgress {
        get {
            if case let .mediaSync(v)? = value { return v }
            return Anki_Sync_MediaSyncProgress()
        }
        set { value = .mediaSync(newValue) }
    }

    public var mediaCheck: String {
        get {
            if case let .mediaCheck(v)? = value { return v }
            return String()
        }
        set { value = .mediaCheck(newValue) }
    }

    public var fullSync: Anki_Collection_Progress.FullSync {
        get {
            if case let .fullSync(v)? = value { return v }
            return Anki_Collection_Progress.FullSync()
        }
        set { value = .fullSync(newValue) }
    }

    public var normalSync: Anki_Collection_Progress.NormalSync {
        get {
            if case let .normalSync(v)? = value { return v }
            return Anki_Collection_Progress.NormalSync()
        }
        set { value = .normalSync(newValue) }
    }

    public var databaseCheck: Anki_Collection_Progress.DatabaseCheck {
        get {
            if case let .databaseCheck(v)? = value { return v }
            return Anki_Collection_Progress.DatabaseCheck()
        }
        set { value = .databaseCheck(newValue) }
    }

    public var importing: String {
        get {
            if case let .importing(v)? = value { return v }
            return String()
        }
        set { value = .importing(newValue) }
    }

    public var exporting: String {
        get {
            if case let .exporting(v)? = value { return v }
            return String()
        }
        set { value = .exporting(newValue) }
    }

    public var computeParams: Anki_Collection_ComputeParamsProgress {
        get {
            if case let .computeParams(v)? = value { return v }
            return Anki_Collection_ComputeParamsProgress()
        }
        set { value = .computeParams(newValue) }
    }

    public var computeRetention: Anki_Collection_ComputeRetentionProgress {
        get {
            if case let .computeRetention(v)? = value { return v }
            return Anki_Collection_ComputeRetentionProgress()
        }
        set { value = .computeRetention(newValue) }
    }

    public var computeMemory: Anki_Collection_ComputeMemoryProgress {
        get {
            if case let .computeMemory(v)? = value { return v }
            return Anki_Collection_ComputeMemoryProgress()
        }
        set { value = .computeMemory(newValue) }
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum OneOf_Value: Equatable, Sendable {
        case none(Anki_Generic_Empty)
        case mediaSync(Anki_Sync_MediaSyncProgress)
        case mediaCheck(String)
        case fullSync(Anki_Collection_Progress.FullSync)
        case normalSync(Anki_Collection_Progress.NormalSync)
        case databaseCheck(Anki_Collection_Progress.DatabaseCheck)
        case importing(String)
        case exporting(String)
        case computeParams(Anki_Collection_ComputeParamsProgress)
        case computeRetention(Anki_Collection_ComputeRetentionProgress)
        case computeMemory(Anki_Collection_ComputeMemoryProgress)
    }

    public struct FullSync: Sendable {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        public var transferred: UInt32 = 0

        public var total: UInt32 = 0

        public var unknownFields = SwiftProtobuf.UnknownStorage()

        public init() {}
    }

    public struct NormalSync: Sendable {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        public var stage: String = .init()

        public var added: String = .init()

        public var removed: String = .init()

        public var unknownFields = SwiftProtobuf.UnknownStorage()

        public init() {}
    }

    public struct DatabaseCheck: Sendable {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        public var stage: String = .init()

        public var stageTotal: UInt32 = 0

        public var stageCurrent: UInt32 = 0

        public var unknownFields = SwiftProtobuf.UnknownStorage()

        public init() {}
    }

    public init() {}
}

public struct Anki_Collection_ComputeParamsProgress: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Current iteration
    public var current: UInt32 = 0

    /// Total iterations
    public var total: UInt32 = 0

    public var reviews: UInt32 = 0

    /// Only used in 'compute all params' case
    public var currentPreset: UInt32 = 0

    /// Only used in 'compute all params' case
    public var totalPresets: UInt32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Collection_ComputeRetentionProgress: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var current: UInt32 = 0

    public var total: UInt32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Collection_ComputeMemoryProgress: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var currentCards: UInt32 = 0

    public var totalCards: UInt32 = 0

    public var label: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Collection_CreateBackupRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var backupFolder: String = .init()

    /// Create a backup even if the configured interval hasn't elapsed yet.
    public var force: Bool = false

    public var waitForCompletion: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Collection_GetCustomColoursResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var colours: [String] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "anki.collection"

extension Anki_Collection_OpenCollectionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".OpenCollectionRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}collection_path\0\u{3}media_folder_path\0\u{3}media_db_path\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &collectionPath)
                case 2: try decoder.decodeSingularStringField(value: &mediaFolderPath)
                case 3: try decoder.decodeSingularStringField(value: &mediaDbPath)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !collectionPath.isEmpty {
            try visitor.visitSingularStringField(value: collectionPath, fieldNumber: 1)
        }
        if !mediaFolderPath.isEmpty {
            try visitor.visitSingularStringField(value: mediaFolderPath, fieldNumber: 2)
        }
        if !mediaDbPath.isEmpty {
            try visitor.visitSingularStringField(value: mediaDbPath, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_OpenCollectionRequest,
                           rhs: Anki_Collection_OpenCollectionRequest) -> Bool {
        if lhs.collectionPath != rhs.collectionPath { return false }
        if lhs.mediaFolderPath != rhs.mediaFolderPath { return false }
        if lhs.mediaDbPath != rhs.mediaDbPath { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_CloseCollectionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".CloseCollectionRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}downgrade_to_schema11\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularBoolField(value: &downgradeToSchema11)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if downgradeToSchema11 != false {
            try visitor.visitSingularBoolField(value: downgradeToSchema11, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_CloseCollectionRequest,
                           rhs: Anki_Collection_CloseCollectionRequest) -> Bool {
        if lhs.downgradeToSchema11 != rhs.downgradeToSchema11 { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_CheckDatabaseResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".CheckDatabaseResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}problems\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedStringField(value: &problems)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !problems.isEmpty {
            try visitor.visitRepeatedStringField(value: problems, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_CheckDatabaseResponse,
                           rhs: Anki_Collection_CheckDatabaseResponse) -> Bool {
        if lhs.problems != rhs.problems { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_OpChanges: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".OpChanges"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{1}card\0\u{1}note\0\u{1}deck\0\u{1}tag\0\u{1}notetype\0\u{1}config\0\u{3}browser_table\0\u{3}browser_sidebar\0\u{3}note_text\0\u{3}study_queues\0\u{3}deck_config\0\u{1}mtime\0"
        )

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularBoolField(value: &card)
                case 2: try decoder.decodeSingularBoolField(value: &note)
                case 3: try decoder.decodeSingularBoolField(value: &deck)
                case 4: try decoder.decodeSingularBoolField(value: &tag)
                case 5: try decoder.decodeSingularBoolField(value: &notetype)
                case 6: try decoder.decodeSingularBoolField(value: &config)
                case 7: try decoder.decodeSingularBoolField(value: &browserTable)
                case 8: try decoder.decodeSingularBoolField(value: &browserSidebar)
                case 9: try decoder.decodeSingularBoolField(value: &noteText)
                case 10: try decoder.decodeSingularBoolField(value: &studyQueues)
                case 11: try decoder.decodeSingularBoolField(value: &deckConfig)
                case 12: try decoder.decodeSingularBoolField(value: &mtime)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if card != false {
            try visitor.visitSingularBoolField(value: card, fieldNumber: 1)
        }
        if note != false {
            try visitor.visitSingularBoolField(value: note, fieldNumber: 2)
        }
        if deck != false {
            try visitor.visitSingularBoolField(value: deck, fieldNumber: 3)
        }
        if tag != false {
            try visitor.visitSingularBoolField(value: tag, fieldNumber: 4)
        }
        if notetype != false {
            try visitor.visitSingularBoolField(value: notetype, fieldNumber: 5)
        }
        if config != false {
            try visitor.visitSingularBoolField(value: config, fieldNumber: 6)
        }
        if browserTable != false {
            try visitor.visitSingularBoolField(value: browserTable, fieldNumber: 7)
        }
        if browserSidebar != false {
            try visitor.visitSingularBoolField(value: browserSidebar, fieldNumber: 8)
        }
        if noteText != false {
            try visitor.visitSingularBoolField(value: noteText, fieldNumber: 9)
        }
        if studyQueues != false {
            try visitor.visitSingularBoolField(value: studyQueues, fieldNumber: 10)
        }
        if deckConfig != false {
            try visitor.visitSingularBoolField(value: deckConfig, fieldNumber: 11)
        }
        if mtime != false {
            try visitor.visitSingularBoolField(value: mtime, fieldNumber: 12)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_OpChanges, rhs: Anki_Collection_OpChanges) -> Bool {
        if lhs.card != rhs.card { return false }
        if lhs.note != rhs.note { return false }
        if lhs.deck != rhs.deck { return false }
        if lhs.tag != rhs.tag { return false }
        if lhs.notetype != rhs.notetype { return false }
        if lhs.config != rhs.config { return false }
        if lhs.deckConfig != rhs.deckConfig { return false }
        if lhs.mtime != rhs.mtime { return false }
        if lhs.browserTable != rhs.browserTable { return false }
        if lhs.browserSidebar != rhs.browserSidebar { return false }
        if lhs.noteText != rhs.noteText { return false }
        if lhs.studyQueues != rhs.studyQueues { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_OpChangesOnly: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".OpChangesOnly"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}changes\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_changes)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _changes {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_OpChangesOnly, rhs: Anki_Collection_OpChangesOnly) -> Bool {
        if lhs._changes != rhs._changes { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_OpChangesWithCount: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".OpChangesWithCount"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}changes\0\u{1}count\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_changes)
                case 2: try decoder.decodeSingularUInt32Field(value: &count)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _changes {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if count != 0 {
            try visitor.visitSingularUInt32Field(value: count, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_OpChangesWithCount, rhs: Anki_Collection_OpChangesWithCount) -> Bool {
        if lhs._changes != rhs._changes { return false }
        if lhs.count != rhs.count { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_OpChangesWithId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".OpChangesWithId"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}changes\0\u{1}id\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_changes)
                case 2: try decoder.decodeSingularInt64Field(value: &id)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _changes {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if id != 0 {
            try visitor.visitSingularInt64Field(value: id, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_OpChangesWithId, rhs: Anki_Collection_OpChangesWithId) -> Bool {
        if lhs._changes != rhs._changes { return false }
        if lhs.id != rhs.id { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_UndoStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".UndoStatus"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}undo\0\u{1}redo\0\u{3}last_step\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &undo)
                case 2: try decoder.decodeSingularStringField(value: &redo)
                case 3: try decoder.decodeSingularUInt32Field(value: &lastStep)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !undo.isEmpty {
            try visitor.visitSingularStringField(value: undo, fieldNumber: 1)
        }
        if !redo.isEmpty {
            try visitor.visitSingularStringField(value: redo, fieldNumber: 2)
        }
        if lastStep != 0 {
            try visitor.visitSingularUInt32Field(value: lastStep, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_UndoStatus, rhs: Anki_Collection_UndoStatus) -> Bool {
        if lhs.undo != rhs.undo { return false }
        if lhs.redo != rhs.redo { return false }
        if lhs.lastStep != rhs.lastStep { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_OpChangesAfterUndo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".OpChangesAfterUndo"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{1}changes\0\u{1}operation\0\u{3}reverted_to_timestamp\0\u{3}new_status\0\u{1}counter\0"
        )

    fileprivate class _StorageClass {
        var _changes: Anki_Collection_OpChanges?
        var _operation: String = .init()
        var _revertedToTimestamp: Int64 = 0
        var _newStatus: Anki_Collection_UndoStatus?
        var _counter: UInt32 = 0

        /// This property is used as the initial default value for new instances of the type.
        /// The type itself is protecting the reference to its storage via CoW semantics.
        /// This will force a copy to be made of this reference when the first mutation occurs;
        /// hence, it is safe to mark this as `nonisolated(unsafe)`.
        nonisolated(unsafe) static let defaultInstance = _StorageClass()

        private init() {}

        init(copying source: _StorageClass) {
            _changes = source._changes
            _operation = source._operation
            _revertedToTimestamp = source._revertedToTimestamp
            _newStatus = source._newStatus
            _counter = source._counter
        }
    }

    fileprivate mutating func _uniqueStorage() -> _StorageClass {
        if !isKnownUniquelyReferenced(&_storage) {
            _storage = _StorageClass(copying: _storage)
        }
        return _storage
    }

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        _ = _uniqueStorage()
        try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
            while let fieldNumber = try decoder.nextFieldNumber() {
                // The use of inline closures is to circumvent an issue where the compiler
                // allocates stack space for every case branch when no optimizations are
                // enabled. https://github.com/apple/swift-protobuf/issues/1034
                switch fieldNumber {
                    case 1: try decoder.decodeSingularMessageField(value: &_storage._changes)
                    case 2: try decoder.decodeSingularStringField(value: &_storage._operation)
                    case 3: try decoder.decodeSingularInt64Field(value: &_storage._revertedToTimestamp)
                    case 4: try decoder.decodeSingularMessageField(value: &_storage._newStatus)
                    case 5: try decoder.decodeSingularUInt32Field(value: &_storage._counter)
                    default: break
                }
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every if/case branch local when no optimizations
            // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
            // https://github.com/apple/swift-protobuf/issues/1182
            try { if let v = _storage._changes {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
            } }()
            if !_storage._operation.isEmpty {
                try visitor.visitSingularStringField(value: _storage._operation, fieldNumber: 2)
            }
            if _storage._revertedToTimestamp != 0 {
                try visitor.visitSingularInt64Field(value: _storage._revertedToTimestamp, fieldNumber: 3)
            }
            try { if let v = _storage._newStatus {
                try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
            } }()
            if _storage._counter != 0 {
                try visitor.visitSingularUInt32Field(value: _storage._counter, fieldNumber: 5)
            }
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_OpChangesAfterUndo, rhs: Anki_Collection_OpChangesAfterUndo) -> Bool {
        if lhs._storage !== rhs._storage {
            let storagesAreEqual: Bool = withExtendedLifetime((
                lhs._storage,
                rhs._storage
            )) { (_args: (_StorageClass, _StorageClass)) in
                let _storage = _args.0
                let rhs_storage = _args.1
                if _storage._changes != rhs_storage._changes { return false }
                if _storage._operation != rhs_storage._operation { return false }
                if _storage._revertedToTimestamp != rhs_storage._revertedToTimestamp { return false }
                if _storage._newStatus != rhs_storage._newStatus { return false }
                if _storage._counter != rhs_storage._counter { return false }
                return true
            }
            if !storagesAreEqual { return false }
        }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_Progress: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".Progress"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{1}none\0\u{3}media_sync\0\u{3}media_check\0\u{3}full_sync\0\u{3}normal_sync\0\u{3}database_check\0\u{1}importing\0\u{1}exporting\0\u{3}compute_params\0\u{3}compute_retention\0\u{3}compute_memory\0"
        )

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try {
                        var v: Anki_Generic_Empty?
                        var hadOneofValue = false
                        if let current = self.value {
                            hadOneofValue = true
                            if case let .none(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.value = .none(v)
                        }
                    }()
                case 2: try {
                        var v: Anki_Sync_MediaSyncProgress?
                        var hadOneofValue = false
                        if let current = self.value {
                            hadOneofValue = true
                            if case let .mediaSync(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.value = .mediaSync(v)
                        }
                    }()
                case 3: try {
                        var v: String?
                        try decoder.decodeSingularStringField(value: &v)
                        if let v {
                            if self.value != nil { try decoder.handleConflictingOneOf() }
                            self.value = .mediaCheck(v)
                        }
                    }()
                case 4: try {
                        var v: Anki_Collection_Progress.FullSync?
                        var hadOneofValue = false
                        if let current = self.value {
                            hadOneofValue = true
                            if case let .fullSync(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.value = .fullSync(v)
                        }
                    }()
                case 5: try {
                        var v: Anki_Collection_Progress.NormalSync?
                        var hadOneofValue = false
                        if let current = self.value {
                            hadOneofValue = true
                            if case let .normalSync(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.value = .normalSync(v)
                        }
                    }()
                case 6: try {
                        var v: Anki_Collection_Progress.DatabaseCheck?
                        var hadOneofValue = false
                        if let current = self.value {
                            hadOneofValue = true
                            if case let .databaseCheck(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.value = .databaseCheck(v)
                        }
                    }()
                case 7: try {
                        var v: String?
                        try decoder.decodeSingularStringField(value: &v)
                        if let v {
                            if self.value != nil { try decoder.handleConflictingOneOf() }
                            self.value = .importing(v)
                        }
                    }()
                case 8: try {
                        var v: String?
                        try decoder.decodeSingularStringField(value: &v)
                        if let v {
                            if self.value != nil { try decoder.handleConflictingOneOf() }
                            self.value = .exporting(v)
                        }
                    }()
                case 9: try {
                        var v: Anki_Collection_ComputeParamsProgress?
                        var hadOneofValue = false
                        if let current = self.value {
                            hadOneofValue = true
                            if case let .computeParams(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.value = .computeParams(v)
                        }
                    }()
                case 10: try {
                        var v: Anki_Collection_ComputeRetentionProgress?
                        var hadOneofValue = false
                        if let current = self.value {
                            hadOneofValue = true
                            if case let .computeRetention(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.value = .computeRetention(v)
                        }
                    }()
                case 11: try {
                        var v: Anki_Collection_ComputeMemoryProgress?
                        var hadOneofValue = false
                        if let current = self.value {
                            hadOneofValue = true
                            if case let .computeMemory(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.value = .computeMemory(v)
                        }
                    }()
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        switch value {
            case .none?: try {
                    guard case let .none(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
                }()
            case .mediaSync?: try {
                    guard case let .mediaSync(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
                }()
            case .mediaCheck?: try {
                    guard case let .mediaCheck(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularStringField(value: v, fieldNumber: 3)
                }()
            case .fullSync?: try {
                    guard case let .fullSync(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
                }()
            case .normalSync?: try {
                    guard case let .normalSync(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
                }()
            case .databaseCheck?: try {
                    guard case let .databaseCheck(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
                }()
            case .importing?: try {
                    guard case let .importing(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularStringField(value: v, fieldNumber: 7)
                }()
            case .exporting?: try {
                    guard case let .exporting(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularStringField(value: v, fieldNumber: 8)
                }()
            case .computeParams?: try {
                    guard case let .computeParams(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
                }()
            case .computeRetention?: try {
                    guard case let .computeRetention(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
                }()
            case .computeMemory?: try {
                    guard case let .computeMemory(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
                }()
            case nil: break
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_Progress, rhs: Anki_Collection_Progress) -> Bool {
        if lhs.value != rhs.value { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_Progress.FullSync: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = Anki_Collection_Progress.protoMessageName + ".FullSync"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}transferred\0\u{1}total\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularUInt32Field(value: &transferred)
                case 2: try decoder.decodeSingularUInt32Field(value: &total)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if transferred != 0 {
            try visitor.visitSingularUInt32Field(value: transferred, fieldNumber: 1)
        }
        if total != 0 {
            try visitor.visitSingularUInt32Field(value: total, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_Progress.FullSync, rhs: Anki_Collection_Progress.FullSync) -> Bool {
        if lhs.transferred != rhs.transferred { return false }
        if lhs.total != rhs.total { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_Progress.NormalSync: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = Anki_Collection_Progress.protoMessageName + ".NormalSync"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}stage\0\u{1}added\0\u{1}removed\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &stage)
                case 2: try decoder.decodeSingularStringField(value: &added)
                case 3: try decoder.decodeSingularStringField(value: &removed)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !stage.isEmpty {
            try visitor.visitSingularStringField(value: stage, fieldNumber: 1)
        }
        if !added.isEmpty {
            try visitor.visitSingularStringField(value: added, fieldNumber: 2)
        }
        if !removed.isEmpty {
            try visitor.visitSingularStringField(value: removed, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_Progress.NormalSync, rhs: Anki_Collection_Progress.NormalSync) -> Bool {
        if lhs.stage != rhs.stage { return false }
        if lhs.added != rhs.added { return false }
        if lhs.removed != rhs.removed { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_Progress.DatabaseCheck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = Anki_Collection_Progress.protoMessageName + ".DatabaseCheck"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}stage\0\u{3}stage_total\0\u{3}stage_current\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &stage)
                case 2: try decoder.decodeSingularUInt32Field(value: &stageTotal)
                case 3: try decoder.decodeSingularUInt32Field(value: &stageCurrent)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !stage.isEmpty {
            try visitor.visitSingularStringField(value: stage, fieldNumber: 1)
        }
        if stageTotal != 0 {
            try visitor.visitSingularUInt32Field(value: stageTotal, fieldNumber: 2)
        }
        if stageCurrent != 0 {
            try visitor.visitSingularUInt32Field(value: stageCurrent, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_Progress.DatabaseCheck,
                           rhs: Anki_Collection_Progress.DatabaseCheck) -> Bool {
        if lhs.stage != rhs.stage { return false }
        if lhs.stageTotal != rhs.stageTotal { return false }
        if lhs.stageCurrent != rhs.stageCurrent { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_ComputeParamsProgress: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ComputeParamsProgress"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}current\0\u{1}total\0\u{1}reviews\0\u{3}current_preset\0\u{3}total_presets\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularUInt32Field(value: &current)
                case 2: try decoder.decodeSingularUInt32Field(value: &total)
                case 3: try decoder.decodeSingularUInt32Field(value: &reviews)
                case 4: try decoder.decodeSingularUInt32Field(value: &currentPreset)
                case 5: try decoder.decodeSingularUInt32Field(value: &totalPresets)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if current != 0 {
            try visitor.visitSingularUInt32Field(value: current, fieldNumber: 1)
        }
        if total != 0 {
            try visitor.visitSingularUInt32Field(value: total, fieldNumber: 2)
        }
        if reviews != 0 {
            try visitor.visitSingularUInt32Field(value: reviews, fieldNumber: 3)
        }
        if currentPreset != 0 {
            try visitor.visitSingularUInt32Field(value: currentPreset, fieldNumber: 4)
        }
        if totalPresets != 0 {
            try visitor.visitSingularUInt32Field(value: totalPresets, fieldNumber: 5)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_ComputeParamsProgress,
                           rhs: Anki_Collection_ComputeParamsProgress) -> Bool {
        if lhs.current != rhs.current { return false }
        if lhs.total != rhs.total { return false }
        if lhs.reviews != rhs.reviews { return false }
        if lhs.currentPreset != rhs.currentPreset { return false }
        if lhs.totalPresets != rhs.totalPresets { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_ComputeRetentionProgress: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ComputeRetentionProgress"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}current\0\u{1}total\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularUInt32Field(value: &current)
                case 2: try decoder.decodeSingularUInt32Field(value: &total)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if current != 0 {
            try visitor.visitSingularUInt32Field(value: current, fieldNumber: 1)
        }
        if total != 0 {
            try visitor.visitSingularUInt32Field(value: total, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_ComputeRetentionProgress,
                           rhs: Anki_Collection_ComputeRetentionProgress) -> Bool {
        if lhs.current != rhs.current { return false }
        if lhs.total != rhs.total { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_ComputeMemoryProgress: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ComputeMemoryProgress"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}current_cards\0\u{3}total_cards\0\u{1}label\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularUInt32Field(value: &currentCards)
                case 2: try decoder.decodeSingularUInt32Field(value: &totalCards)
                case 3: try decoder.decodeSingularStringField(value: &label)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if currentCards != 0 {
            try visitor.visitSingularUInt32Field(value: currentCards, fieldNumber: 1)
        }
        if totalCards != 0 {
            try visitor.visitSingularUInt32Field(value: totalCards, fieldNumber: 2)
        }
        if !label.isEmpty {
            try visitor.visitSingularStringField(value: label, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_ComputeMemoryProgress,
                           rhs: Anki_Collection_ComputeMemoryProgress) -> Bool {
        if lhs.currentCards != rhs.currentCards { return false }
        if lhs.totalCards != rhs.totalCards { return false }
        if lhs.label != rhs.label { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_CreateBackupRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".CreateBackupRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}backup_folder\0\u{1}force\0\u{3}wait_for_completion\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &backupFolder)
                case 2: try decoder.decodeSingularBoolField(value: &force)
                case 3: try decoder.decodeSingularBoolField(value: &waitForCompletion)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !backupFolder.isEmpty {
            try visitor.visitSingularStringField(value: backupFolder, fieldNumber: 1)
        }
        if force != false {
            try visitor.visitSingularBoolField(value: force, fieldNumber: 2)
        }
        if waitForCompletion != false {
            try visitor.visitSingularBoolField(value: waitForCompletion, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_CreateBackupRequest, rhs: Anki_Collection_CreateBackupRequest) -> Bool {
        if lhs.backupFolder != rhs.backupFolder { return false }
        if lhs.force != rhs.force { return false }
        if lhs.waitForCompletion != rhs.waitForCompletion { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Collection_GetCustomColoursResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".GetCustomColoursResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}colours\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedStringField(value: &colours)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !colours.isEmpty {
            try visitor.visitRepeatedStringField(value: colours, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Collection_GetCustomColoursResponse,
                           rhs: Anki_Collection_GetCustomColoursResponse) -> Bool {
        if lhs.colours != rhs.colours { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
