// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/frontend.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct Anki_Frontend_SchedulingStatesWithContext: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var states: Anki_Scheduler_SchedulingStates {
        get { _states ?? Anki_Scheduler_SchedulingStates() }
        set { _states = newValue }
    }

    /// Returns true if `states` has been explicitly set.
    public var hasStates: Bool {
        _states != nil
    }

    /// Clears the value of `states`. Subsequent reads from it will return its default value.
    public mutating func clearStates() {
        _states = nil
    }

    public var context: Anki_Scheduler_SchedulingContext {
        get { _context ?? Anki_Scheduler_SchedulingContext() }
        set { _context = newValue }
    }

    /// Returns true if `context` has been explicitly set.
    public var hasContext: Bool {
        _context != nil
    }

    /// Clears the value of `context`. Subsequent reads from it will return its default value.
    public mutating func clearContext() {
        _context = nil
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _states: Anki_Scheduler_SchedulingStates?
    fileprivate var _context: Anki_Scheduler_SchedulingContext?
}

public struct Anki_Frontend_SetSchedulingStatesRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var key: String = .init()

    public var states: Anki_Scheduler_SchedulingStates {
        get { _states ?? Anki_Scheduler_SchedulingStates() }
        set { _states = newValue }
    }

    /// Returns true if `states` has been explicitly set.
    public var hasStates: Bool {
        _states != nil
    }

    /// Clears the value of `states`. Subsequent reads from it will return its default value.
    public mutating func clearStates() {
        _states = nil
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _states: Anki_Scheduler_SchedulingStates?
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "anki.frontend"

extension Anki_Frontend_SchedulingStatesWithContext: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".SchedulingStatesWithContext"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}states\0\u{1}context\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_states)
                case 2: try decoder.decodeSingularMessageField(value: &_context)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _states {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        try { if let v = self._context {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_Frontend_SchedulingStatesWithContext,
        rhs: Anki_Frontend_SchedulingStatesWithContext
    ) -> Bool {
        if lhs._states != rhs._states { return false }
        if lhs._context != rhs._context { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Frontend_SetSchedulingStatesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".SetSchedulingStatesRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{1}states\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &key)
                case 2: try decoder.decodeSingularMessageField(value: &_states)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !key.isEmpty {
            try visitor.visitSingularStringField(value: key, fieldNumber: 1)
        }
        try { if let v = self._states {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Frontend_SetSchedulingStatesRequest,
                           rhs: Anki_Frontend_SetSchedulingStatesRequest) -> Bool {
        if lhs.key != rhs.key { return false }
        if lhs._states != rhs._states { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
