// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/image_occlusion.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

#if canImport(FoundationEssentials)
    import FoundationEssentials
#else
    import Foundation
#endif
import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct Anki_ImageOcclusion_GetImageForOcclusionRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var path: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_ImageOcclusion_GetImageForOcclusionResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var data: Data = .init()

    public var name: String = .init()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_ImageOcclusion_AddImageOcclusionNoteRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var imagePath: String = .init()

    public var occlusions: String = .init()

    public var header: String = .init()

    public var backExtra: String = .init()

    public var tags: [String] = []

    public var notetypeID: Int64 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_ImageOcclusion_GetImageOcclusionNoteRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var noteID: Int64 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_ImageOcclusion_GetImageOcclusionNoteResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var value: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.OneOf_Value?

    public var note: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionNote {
        get {
            if case let .note(v)? = value { return v }
            return Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionNote()
        }
        set { value = .note(newValue) }
    }

    public var error: String {
        get {
            if case let .error(v)? = value { return v }
            return String()
        }
        set { value = .error(newValue) }
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum OneOf_Value: Equatable, Sendable {
        case note(Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionNote)
        case error(String)
    }

    public struct ImageOcclusionProperty: Sendable {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        public var name: String = .init()

        public var value: String = .init()

        public var unknownFields = SwiftProtobuf.UnknownStorage()

        public init() {}
    }

    public struct ImageOcclusionShape: Sendable {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        public var shape: String = .init()

        public var properties: [Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionProperty] = []

        public var unknownFields = SwiftProtobuf.UnknownStorage()

        public init() {}
    }

    public struct ImageOcclusion: Sendable {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        public var shapes: [Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionShape] = []

        public var ordinal: UInt32 = 0

        public var unknownFields = SwiftProtobuf.UnknownStorage()

        public init() {}
    }

    public struct ImageOcclusionNote: Sendable {
        // SwiftProtobuf.Message conformance is added in an extension below. See the
        // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
        // methods supported on all messages.

        public var imageData: Data = .init()

        public var occlusions: [Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusion] = []

        public var header: String = .init()

        public var backExtra: String = .init()

        public var tags: [String] = []

        public var imageFileName: String = .init()

        public var occludeInactive: Bool = false

        public var unknownFields = SwiftProtobuf.UnknownStorage()

        public init() {}
    }

    public init() {}
}

public struct Anki_ImageOcclusion_UpdateImageOcclusionNoteRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var noteID: Int64 = 0

    public var occlusions: String = .init()

    public var header: String = .init()

    public var backExtra: String = .init()

    public var tags: [String] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_ImageOcclusion_GetImageOcclusionFieldsRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var notetypeID: Int64 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_ImageOcclusion_GetImageOcclusionFieldsResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var fields: Anki_ImageOcclusion_ImageOcclusionFieldIndexes {
        get { _fields ?? Anki_ImageOcclusion_ImageOcclusionFieldIndexes() }
        set { _fields = newValue }
    }

    /// Returns true if `fields` has been explicitly set.
    public var hasFields: Bool {
        _fields != nil
    }

    /// Clears the value of `fields`. Subsequent reads from it will return its default value.
    public mutating func clearFields() {
        _fields = nil
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _fields: Anki_ImageOcclusion_ImageOcclusionFieldIndexes?
}

public struct Anki_ImageOcclusion_ImageOcclusionFieldIndexes: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var occlusions: UInt32 = 0

    public var image: UInt32 = 0

    public var header: UInt32 = 0

    public var backExtra: UInt32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "anki.image_occlusion"

extension Anki_ImageOcclusion_GetImageForOcclusionRequest: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".GetImageForOcclusionRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}path\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &path)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !path.isEmpty {
            try visitor.visitSingularStringField(value: path, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_ImageOcclusion_GetImageForOcclusionRequest,
        rhs: Anki_ImageOcclusion_GetImageForOcclusionRequest
    ) -> Bool {
        if lhs.path != rhs.path { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImageOcclusion_GetImageForOcclusionResponse: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".GetImageForOcclusionResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}data\0\u{1}name\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularBytesField(value: &data)
                case 2: try decoder.decodeSingularStringField(value: &name)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !data.isEmpty {
            try visitor.visitSingularBytesField(value: data, fieldNumber: 1)
        }
        if !name.isEmpty {
            try visitor.visitSingularStringField(value: name, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_ImageOcclusion_GetImageForOcclusionResponse,
        rhs: Anki_ImageOcclusion_GetImageForOcclusionResponse
    ) -> Bool {
        if lhs.data != rhs.data { return false }
        if lhs.name != rhs.name { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImageOcclusion_AddImageOcclusionNoteRequest: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".AddImageOcclusionNoteRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{3}image_path\0\u{1}occlusions\0\u{1}header\0\u{3}back_extra\0\u{1}tags\0\u{3}notetype_id\0"
        )

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &imagePath)
                case 2: try decoder.decodeSingularStringField(value: &occlusions)
                case 3: try decoder.decodeSingularStringField(value: &header)
                case 4: try decoder.decodeSingularStringField(value: &backExtra)
                case 5: try decoder.decodeRepeatedStringField(value: &tags)
                case 6: try decoder.decodeSingularInt64Field(value: &notetypeID)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !imagePath.isEmpty {
            try visitor.visitSingularStringField(value: imagePath, fieldNumber: 1)
        }
        if !occlusions.isEmpty {
            try visitor.visitSingularStringField(value: occlusions, fieldNumber: 2)
        }
        if !header.isEmpty {
            try visitor.visitSingularStringField(value: header, fieldNumber: 3)
        }
        if !backExtra.isEmpty {
            try visitor.visitSingularStringField(value: backExtra, fieldNumber: 4)
        }
        if !tags.isEmpty {
            try visitor.visitRepeatedStringField(value: tags, fieldNumber: 5)
        }
        if notetypeID != 0 {
            try visitor.visitSingularInt64Field(value: notetypeID, fieldNumber: 6)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_ImageOcclusion_AddImageOcclusionNoteRequest,
        rhs: Anki_ImageOcclusion_AddImageOcclusionNoteRequest
    ) -> Bool {
        if lhs.imagePath != rhs.imagePath { return false }
        if lhs.occlusions != rhs.occlusions { return false }
        if lhs.header != rhs.header { return false }
        if lhs.backExtra != rhs.backExtra { return false }
        if lhs.tags != rhs.tags { return false }
        if lhs.notetypeID != rhs.notetypeID { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImageOcclusion_GetImageOcclusionNoteRequest: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".GetImageOcclusionNoteRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}note_id\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularInt64Field(value: &noteID)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if noteID != 0 {
            try visitor.visitSingularInt64Field(value: noteID, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_ImageOcclusion_GetImageOcclusionNoteRequest,
        rhs: Anki_ImageOcclusion_GetImageOcclusionNoteRequest
    ) -> Bool {
        if lhs.noteID != rhs.noteID { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImageOcclusion_GetImageOcclusionNoteResponse: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".GetImageOcclusionNoteResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}note\0\u{1}error\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try {
                        var v: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionNote?
                        var hadOneofValue = false
                        if let current = self.value {
                            hadOneofValue = true
                            if case let .note(m) = current { v = m }
                        }
                        try decoder.decodeSingularMessageField(value: &v)
                        if let v {
                            if hadOneofValue { try decoder.handleConflictingOneOf() }
                            self.value = .note(v)
                        }
                    }()
                case 2: try {
                        var v: String?
                        try decoder.decodeSingularStringField(value: &v)
                        if let v {
                            if self.value != nil { try decoder.handleConflictingOneOf() }
                            self.value = .error(v)
                        }
                    }()
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        switch value {
            case .note?: try {
                    guard case let .note(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
                }()
            case .error?: try {
                    guard case let .error(v)? = self.value else { preconditionFailure() }
                    try visitor.visitSingularStringField(value: v, fieldNumber: 2)
                }()
            case nil: break
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse,
        rhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse
    ) -> Bool {
        if lhs.value != rhs.value { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionProperty: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = Anki_ImageOcclusion_GetImageOcclusionNoteResponse.protoMessageName + ".ImageOcclusionProperty"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}value\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &name)
                case 2: try decoder.decodeSingularStringField(value: &value)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !name.isEmpty {
            try visitor.visitSingularStringField(value: name, fieldNumber: 1)
        }
        if !value.isEmpty {
            try visitor.visitSingularStringField(value: value, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionProperty,
        rhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionProperty
    ) -> Bool {
        if lhs.name != rhs.name { return false }
        if lhs.value != rhs.value { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionShape: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = Anki_ImageOcclusion_GetImageOcclusionNoteResponse.protoMessageName + ".ImageOcclusionShape"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}shape\0\u{1}properties\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularStringField(value: &shape)
                case 2: try decoder.decodeRepeatedMessageField(value: &properties)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !shape.isEmpty {
            try visitor.visitSingularStringField(value: shape, fieldNumber: 1)
        }
        if !properties.isEmpty {
            try visitor.visitRepeatedMessageField(value: properties, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionShape,
        rhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionShape
    ) -> Bool {
        if lhs.shape != rhs.shape { return false }
        if lhs.properties != rhs.properties { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusion: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = Anki_ImageOcclusion_GetImageOcclusionNoteResponse.protoMessageName + ".ImageOcclusion"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}shapes\0\u{1}ordinal\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedMessageField(value: &shapes)
                case 2: try decoder.decodeSingularUInt32Field(value: &ordinal)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !shapes.isEmpty {
            try visitor.visitRepeatedMessageField(value: shapes, fieldNumber: 1)
        }
        if ordinal != 0 {
            try visitor.visitSingularUInt32Field(value: ordinal, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusion,
        rhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusion
    ) -> Bool {
        if lhs.shapes != rhs.shapes { return false }
        if lhs.ordinal != rhs.ordinal { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionNote: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = Anki_ImageOcclusion_GetImageOcclusionNoteResponse.protoMessageName + ".ImageOcclusionNote"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{3}image_data\0\u{1}occlusions\0\u{1}header\0\u{3}back_extra\0\u{1}tags\0\u{3}image_file_name\0\u{3}occlude_inactive\0"
        )

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularBytesField(value: &imageData)
                case 2: try decoder.decodeRepeatedMessageField(value: &occlusions)
                case 3: try decoder.decodeSingularStringField(value: &header)
                case 4: try decoder.decodeSingularStringField(value: &backExtra)
                case 5: try decoder.decodeRepeatedStringField(value: &tags)
                case 6: try decoder.decodeSingularStringField(value: &imageFileName)
                case 7: try decoder.decodeSingularBoolField(value: &occludeInactive)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !imageData.isEmpty {
            try visitor.visitSingularBytesField(value: imageData, fieldNumber: 1)
        }
        if !occlusions.isEmpty {
            try visitor.visitRepeatedMessageField(value: occlusions, fieldNumber: 2)
        }
        if !header.isEmpty {
            try visitor.visitSingularStringField(value: header, fieldNumber: 3)
        }
        if !backExtra.isEmpty {
            try visitor.visitSingularStringField(value: backExtra, fieldNumber: 4)
        }
        if !tags.isEmpty {
            try visitor.visitRepeatedStringField(value: tags, fieldNumber: 5)
        }
        if !imageFileName.isEmpty {
            try visitor.visitSingularStringField(value: imageFileName, fieldNumber: 6)
        }
        if occludeInactive != false {
            try visitor.visitSingularBoolField(value: occludeInactive, fieldNumber: 7)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionNote,
        rhs: Anki_ImageOcclusion_GetImageOcclusionNoteResponse.ImageOcclusionNote
    ) -> Bool {
        if lhs.imageData != rhs.imageData { return false }
        if lhs.occlusions != rhs.occlusions { return false }
        if lhs.header != rhs.header { return false }
        if lhs.backExtra != rhs.backExtra { return false }
        if lhs.tags != rhs.tags { return false }
        if lhs.imageFileName != rhs.imageFileName { return false }
        if lhs.occludeInactive != rhs.occludeInactive { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImageOcclusion_UpdateImageOcclusionNoteRequest: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".UpdateImageOcclusionNoteRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}note_id\0\u{1}occlusions\0\u{1}header\0\u{3}back_extra\0\u{1}tags\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularInt64Field(value: &noteID)
                case 2: try decoder.decodeSingularStringField(value: &occlusions)
                case 3: try decoder.decodeSingularStringField(value: &header)
                case 4: try decoder.decodeSingularStringField(value: &backExtra)
                case 5: try decoder.decodeRepeatedStringField(value: &tags)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if noteID != 0 {
            try visitor.visitSingularInt64Field(value: noteID, fieldNumber: 1)
        }
        if !occlusions.isEmpty {
            try visitor.visitSingularStringField(value: occlusions, fieldNumber: 2)
        }
        if !header.isEmpty {
            try visitor.visitSingularStringField(value: header, fieldNumber: 3)
        }
        if !backExtra.isEmpty {
            try visitor.visitSingularStringField(value: backExtra, fieldNumber: 4)
        }
        if !tags.isEmpty {
            try visitor.visitRepeatedStringField(value: tags, fieldNumber: 5)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_ImageOcclusion_UpdateImageOcclusionNoteRequest,
        rhs: Anki_ImageOcclusion_UpdateImageOcclusionNoteRequest
    ) -> Bool {
        if lhs.noteID != rhs.noteID { return false }
        if lhs.occlusions != rhs.occlusions { return false }
        if lhs.header != rhs.header { return false }
        if lhs.backExtra != rhs.backExtra { return false }
        if lhs.tags != rhs.tags { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImageOcclusion_GetImageOcclusionFieldsRequest: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".GetImageOcclusionFieldsRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}notetype_id\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularInt64Field(value: &notetypeID)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if notetypeID != 0 {
            try visitor.visitSingularInt64Field(value: notetypeID, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_ImageOcclusion_GetImageOcclusionFieldsRequest,
        rhs: Anki_ImageOcclusion_GetImageOcclusionFieldsRequest
    ) -> Bool {
        if lhs.notetypeID != rhs.notetypeID { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImageOcclusion_GetImageOcclusionFieldsResponse: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".GetImageOcclusionFieldsResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fields\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_fields)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _fields {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_ImageOcclusion_GetImageOcclusionFieldsResponse,
        rhs: Anki_ImageOcclusion_GetImageOcclusionFieldsResponse
    ) -> Bool {
        if lhs._fields != rhs._fields { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_ImageOcclusion_ImageOcclusionFieldIndexes: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ImageOcclusionFieldIndexes"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}occlusions\0\u{1}image\0\u{1}header\0\u{3}back_extra\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularUInt32Field(value: &occlusions)
                case 2: try decoder.decodeSingularUInt32Field(value: &image)
                case 3: try decoder.decodeSingularUInt32Field(value: &header)
                case 4: try decoder.decodeSingularUInt32Field(value: &backExtra)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if occlusions != 0 {
            try visitor.visitSingularUInt32Field(value: occlusions, fieldNumber: 1)
        }
        if image != 0 {
            try visitor.visitSingularUInt32Field(value: image, fieldNumber: 2)
        }
        if header != 0 {
            try visitor.visitSingularUInt32Field(value: header, fieldNumber: 3)
        }
        if backExtra != 0 {
            try visitor.visitSingularUInt32Field(value: backExtra, fieldNumber: 4)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (
        lhs: Anki_ImageOcclusion_ImageOcclusionFieldIndexes,
        rhs: Anki_ImageOcclusion_ImageOcclusionFieldIndexes
    ) -> Bool {
        if lhs.occlusions != rhs.occlusions { return false }
        if lhs.image != rhs.image { return false }
        if lhs.header != rhs.header { return false }
        if lhs.backExtra != rhs.backExtra { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}
