// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: anki/notes.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

public struct Anki_Notes_NoteId: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var nid: Int64 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Notes_NoteIds: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var noteIds: [Int64] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Notes_Note: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var id: Int64 = 0

    public var guid: String = .init()

    public var notetypeID: Int64 = 0

    public var mtimeSecs: UInt32 = 0

    public var usn: Int32 = 0

    public var tags: [String] = []

    public var fields: [String] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Notes_AddNoteRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var note: Anki_Notes_Note {
        get { _note ?? Anki_Notes_Note() }
        set { _note = newValue }
    }

    /// Returns true if `note` has been explicitly set.
    public var hasNote: Bool {
        _note != nil
    }

    /// Clears the value of `note`. Subsequent reads from it will return its default value.
    public mutating func clearNote() {
        _note = nil
    }

    public var deckID: Int64 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _note: Anki_Notes_Note?
}

public struct Anki_Notes_AddNoteResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var changes: Anki_Collection_OpChangesWithCount {
        get { _changes ?? Anki_Collection_OpChangesWithCount() }
        set { _changes = newValue }
    }

    /// Returns true if `changes` has been explicitly set.
    public var hasChanges: Bool {
        _changes != nil
    }

    /// Clears the value of `changes`. Subsequent reads from it will return its default value.
    public mutating func clearChanges() {
        _changes = nil
    }

    public var noteID: Int64 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _changes: Anki_Collection_OpChangesWithCount?
}

public struct Anki_Notes_AddNotesRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var requests: [Anki_Notes_AddNoteRequest] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Notes_AddNotesResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var changes: Anki_Collection_OpChanges {
        get { _changes ?? Anki_Collection_OpChanges() }
        set { _changes = newValue }
    }

    /// Returns true if `changes` has been explicitly set.
    public var hasChanges: Bool {
        _changes != nil
    }

    /// Clears the value of `changes`. Subsequent reads from it will return its default value.
    public mutating func clearChanges() {
        _changes = nil
    }

    public var nids: [Int64] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _changes: Anki_Collection_OpChanges?
}

public struct Anki_Notes_UpdateNotesRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var notes: [Anki_Notes_Note] = []

    public var skipUndoEntry: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Notes_DefaultsForAddingRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var homeDeckOfCurrentReviewCard: Int64 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Notes_DeckAndNotetype: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var deckID: Int64 = 0

    public var notetypeID: Int64 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Notes_RemoveNotesRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var noteIds: [Int64] = []

    public var cardIds: [Int64] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Notes_ClozeNumbersInNoteResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var numbers: [UInt32] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Notes_AfterNoteUpdatesRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var nids: [Int64] = []

    public var markNotesModified: Bool = false

    public var generateCards: Bool = false

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Notes_FieldNamesForNotesRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var nids: [Int64] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Notes_FieldNamesForNotesResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var fields: [String] = []

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
}

public struct Anki_Notes_NoteFieldsCheckResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var state: Anki_Notes_NoteFieldsCheckResponse.State = .normal

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum State: SwiftProtobuf.Enum, Swift.CaseIterable {
        public typealias RawValue = Int
        case normal // = 0
        case empty // = 1
        case duplicate // = 2
        case missingCloze // = 3
        case notetypeNotCloze // = 4
        case fieldNotCloze // = 5
        case UNRECOGNIZED(Int)

        public init() {
            self = .normal
        }

        public init?(rawValue: Int) {
            switch rawValue {
                case 0: self = .normal
                case 1: self = .empty
                case 2: self = .duplicate
                case 3: self = .missingCloze
                case 4: self = .notetypeNotCloze
                case 5: self = .fieldNotCloze
                default: self = .UNRECOGNIZED(rawValue)
            }
        }

        public var rawValue: Int {
            switch self {
                case .normal: 0
                case .empty: 1
                case .duplicate: 2
                case .missingCloze: 3
                case .notetypeNotCloze: 4
                case .fieldNotCloze: 5
                case let .UNRECOGNIZED(i): i
            }
        }

        /// The compiler won't synthesize support with the UNRECOGNIZED case.
        public static let allCases: [Anki_Notes_NoteFieldsCheckResponse.State] = [
            .normal,
            .empty,
            .duplicate,
            .missingCloze,
            .notetypeNotCloze,
            .fieldNotCloze,
        ]
    }

    public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "anki.notes"

extension Anki_Notes_NoteId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".NoteId"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}nid\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularInt64Field(value: &nid)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if nid != 0 {
            try visitor.visitSingularInt64Field(value: nid, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_NoteId, rhs: Anki_Notes_NoteId) -> Bool {
        if lhs.nid != rhs.nid { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_NoteIds: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".NoteIds"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}note_ids\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedInt64Field(value: &noteIds)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !noteIds.isEmpty {
            try visitor.visitPackedInt64Field(value: noteIds, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_NoteIds, rhs: Anki_Notes_NoteIds) -> Bool {
        if lhs.noteIds != rhs.noteIds { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_Note: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".Note"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{1}id\0\u{1}guid\0\u{3}notetype_id\0\u{3}mtime_secs\0\u{1}usn\0\u{1}tags\0\u{1}fields\0"
        )

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularInt64Field(value: &id)
                case 2: try decoder.decodeSingularStringField(value: &guid)
                case 3: try decoder.decodeSingularInt64Field(value: &notetypeID)
                case 4: try decoder.decodeSingularUInt32Field(value: &mtimeSecs)
                case 5: try decoder.decodeSingularInt32Field(value: &usn)
                case 6: try decoder.decodeRepeatedStringField(value: &tags)
                case 7: try decoder.decodeRepeatedStringField(value: &fields)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if id != 0 {
            try visitor.visitSingularInt64Field(value: id, fieldNumber: 1)
        }
        if !guid.isEmpty {
            try visitor.visitSingularStringField(value: guid, fieldNumber: 2)
        }
        if notetypeID != 0 {
            try visitor.visitSingularInt64Field(value: notetypeID, fieldNumber: 3)
        }
        if mtimeSecs != 0 {
            try visitor.visitSingularUInt32Field(value: mtimeSecs, fieldNumber: 4)
        }
        if usn != 0 {
            try visitor.visitSingularInt32Field(value: usn, fieldNumber: 5)
        }
        if !tags.isEmpty {
            try visitor.visitRepeatedStringField(value: tags, fieldNumber: 6)
        }
        if !fields.isEmpty {
            try visitor.visitRepeatedStringField(value: fields, fieldNumber: 7)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_Note, rhs: Anki_Notes_Note) -> Bool {
        if lhs.id != rhs.id { return false }
        if lhs.guid != rhs.guid { return false }
        if lhs.notetypeID != rhs.notetypeID { return false }
        if lhs.mtimeSecs != rhs.mtimeSecs { return false }
        if lhs.usn != rhs.usn { return false }
        if lhs.tags != rhs.tags { return false }
        if lhs.fields != rhs.fields { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_AddNoteRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".AddNoteRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}note\0\u{3}deck_id\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_note)
                case 2: try decoder.decodeSingularInt64Field(value: &deckID)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _note {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if deckID != 0 {
            try visitor.visitSingularInt64Field(value: deckID, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_AddNoteRequest, rhs: Anki_Notes_AddNoteRequest) -> Bool {
        if lhs._note != rhs._note { return false }
        if lhs.deckID != rhs.deckID { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_AddNoteResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".AddNoteResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}changes\0\u{3}note_id\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_changes)
                case 2: try decoder.decodeSingularInt64Field(value: &noteID)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _changes {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if noteID != 0 {
            try visitor.visitSingularInt64Field(value: noteID, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_AddNoteResponse, rhs: Anki_Notes_AddNoteResponse) -> Bool {
        if lhs._changes != rhs._changes { return false }
        if lhs.noteID != rhs.noteID { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_AddNotesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".AddNotesRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}requests\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedMessageField(value: &requests)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !requests.isEmpty {
            try visitor.visitRepeatedMessageField(value: requests, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_AddNotesRequest, rhs: Anki_Notes_AddNotesRequest) -> Bool {
        if lhs.requests != rhs.requests { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_AddNotesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".AddNotesResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}changes\0\u{1}nids\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularMessageField(value: &_changes)
                case 2: try decoder.decodeRepeatedInt64Field(value: &nids)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _changes {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        if !nids.isEmpty {
            try visitor.visitPackedInt64Field(value: nids, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_AddNotesResponse, rhs: Anki_Notes_AddNotesResponse) -> Bool {
        if lhs._changes != rhs._changes { return false }
        if lhs.nids != rhs.nids { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_UpdateNotesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".UpdateNotesRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}notes\0\u{3}skip_undo_entry\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedMessageField(value: &notes)
                case 2: try decoder.decodeSingularBoolField(value: &skipUndoEntry)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !notes.isEmpty {
            try visitor.visitRepeatedMessageField(value: notes, fieldNumber: 1)
        }
        if skipUndoEntry != false {
            try visitor.visitSingularBoolField(value: skipUndoEntry, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_UpdateNotesRequest, rhs: Anki_Notes_UpdateNotesRequest) -> Bool {
        if lhs.notes != rhs.notes { return false }
        if lhs.skipUndoEntry != rhs.skipUndoEntry { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_DefaultsForAddingRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".DefaultsForAddingRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}home_deck_of_current_review_card\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularInt64Field(value: &homeDeckOfCurrentReviewCard)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if homeDeckOfCurrentReviewCard != 0 {
            try visitor.visitSingularInt64Field(value: homeDeckOfCurrentReviewCard, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_DefaultsForAddingRequest, rhs: Anki_Notes_DefaultsForAddingRequest) -> Bool {
        if lhs.homeDeckOfCurrentReviewCard != rhs.homeDeckOfCurrentReviewCard { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_DeckAndNotetype: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".DeckAndNotetype"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}deck_id\0\u{3}notetype_id\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularInt64Field(value: &deckID)
                case 2: try decoder.decodeSingularInt64Field(value: &notetypeID)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if deckID != 0 {
            try visitor.visitSingularInt64Field(value: deckID, fieldNumber: 1)
        }
        if notetypeID != 0 {
            try visitor.visitSingularInt64Field(value: notetypeID, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_DeckAndNotetype, rhs: Anki_Notes_DeckAndNotetype) -> Bool {
        if lhs.deckID != rhs.deckID { return false }
        if lhs.notetypeID != rhs.notetypeID { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_RemoveNotesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".RemoveNotesRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}note_ids\0\u{3}card_ids\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedInt64Field(value: &noteIds)
                case 2: try decoder.decodeRepeatedInt64Field(value: &cardIds)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !noteIds.isEmpty {
            try visitor.visitPackedInt64Field(value: noteIds, fieldNumber: 1)
        }
        if !cardIds.isEmpty {
            try visitor.visitPackedInt64Field(value: cardIds, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_RemoveNotesRequest, rhs: Anki_Notes_RemoveNotesRequest) -> Bool {
        if lhs.noteIds != rhs.noteIds { return false }
        if lhs.cardIds != rhs.cardIds { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_ClozeNumbersInNoteResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".ClozeNumbersInNoteResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}numbers\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedUInt32Field(value: &numbers)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !numbers.isEmpty {
            try visitor.visitPackedUInt32Field(value: numbers, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_ClozeNumbersInNoteResponse,
                           rhs: Anki_Notes_ClozeNumbersInNoteResponse) -> Bool {
        if lhs.numbers != rhs.numbers { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_AfterNoteUpdatesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".AfterNoteUpdatesRequest"
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}nids\0\u{3}mark_notes_modified\0\u{3}generate_cards\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedInt64Field(value: &nids)
                case 2: try decoder.decodeSingularBoolField(value: &markNotesModified)
                case 3: try decoder.decodeSingularBoolField(value: &generateCards)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !nids.isEmpty {
            try visitor.visitPackedInt64Field(value: nids, fieldNumber: 1)
        }
        if markNotesModified != false {
            try visitor.visitSingularBoolField(value: markNotesModified, fieldNumber: 2)
        }
        if generateCards != false {
            try visitor.visitSingularBoolField(value: generateCards, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_AfterNoteUpdatesRequest, rhs: Anki_Notes_AfterNoteUpdatesRequest) -> Bool {
        if lhs.nids != rhs.nids { return false }
        if lhs.markNotesModified != rhs.markNotesModified { return false }
        if lhs.generateCards != rhs.generateCards { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_FieldNamesForNotesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".FieldNamesForNotesRequest"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}nids\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedInt64Field(value: &nids)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !nids.isEmpty {
            try visitor.visitPackedInt64Field(value: nids, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_FieldNamesForNotesRequest,
                           rhs: Anki_Notes_FieldNamesForNotesRequest) -> Bool {
        if lhs.nids != rhs.nids { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_FieldNamesForNotesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".FieldNamesForNotesResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}fields\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeRepeatedStringField(value: &fields)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !fields.isEmpty {
            try visitor.visitRepeatedStringField(value: fields, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_FieldNamesForNotesResponse,
                           rhs: Anki_Notes_FieldNamesForNotesResponse) -> Bool {
        if lhs.fields != rhs.fields { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_NoteFieldsCheckResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    public static let protoMessageName: String = _protobuf_package + ".NoteFieldsCheckResponse"
    public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}state\0")

    public mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
                case 1: try decoder.decodeSingularEnumField(value: &state)
                default: break
            }
        }
    }

    public func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if state != .normal {
            try visitor.visitSingularEnumField(value: state, fieldNumber: 1)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    public static func == (lhs: Anki_Notes_NoteFieldsCheckResponse, rhs: Anki_Notes_NoteFieldsCheckResponse) -> Bool {
        if lhs.state != rhs.state { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Anki_Notes_NoteFieldsCheckResponse.State: SwiftProtobuf._ProtoNameProviding {
    public static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{2}\0NORMAL\0\u{1}EMPTY\0\u{1}DUPLICATE\0\u{1}MISSING_CLOZE\0\u{1}NOTETYPE_NOT_CLOZE\0\u{1}FIELD_NOT_CLOZE\0"
        )
}
